/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class ChangePassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChangePassword.class.getName());

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        studentportal = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        mycomplaints = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        myprofile = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        navigation = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        backtoprofile = new javax.swing.JButton();
        changepassword = new javax.swing.JLabel();
        updatepassword = new javax.swing.JLabel();
        resetpasswordpanel = new javax.swing.JPanel();
        newpasswordlabel = new javax.swing.JLabel();
        newpasswordtext = new javax.swing.JTextField();
        confirmnewpasswordlabel = new javax.swing.JLabel();
        confirmnewpasswordtext = new javax.swing.JTextField();
        updatepasswordbutton = new javax.swing.JButton();
        currentpassword = new javax.swing.JLabel();
        currentpasswordtext = new javax.swing.JTextField();
        info = new javax.swing.JPanel();
        desc = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundpanel.setLayout(null);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        backgroundpanel.add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        backgroundpanel.add(profile);
        profile.setBounds(1480, 10, 41, 40);

        studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentportal.setText("Student Portal");
        backgroundpanel.add(studentportal);
        studentportal.setBounds(300, 0, 170, 30);

        welcomeback.setText("Welcome Back");
        backgroundpanel.add(welcomeback);
        welcomeback.setBounds(300, 30, 280, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        backgroundpanel.add(dashboard);
        dashboard.setBounds(-30, 210, 240, 43);

        mycomplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mycomplaints.setForeground(new java.awt.Color(255, 255, 255));
        mycomplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my complaints.png"))); // NOI18N
        mycomplaints.setText("My Complaints\n");
        mycomplaints.setBorderPainted(false);
        mycomplaints.setContentAreaFilled(false);
        backgroundpanel.add(mycomplaints);
        mycomplaints.setBounds(-10, 280, 230, 43);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        backgroundpanel.add(mealroutine);
        mealroutine.setBounds(-30, 350, 260, 43);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        backgroundpanel.add(notice);
        notice.setBounds(0, 420, 140, 43);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        backgroundpanel.add(roomdetails);
        roomdetails.setBounds(0, 490, 200, 43);

        myprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myprofile.setForeground(new java.awt.Color(255, 255, 255));
        myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/myprofile.png"))); // NOI18N
        myprofile.setText("My Profile");
        myprofile.setBorderPainted(false);
        myprofile.setContentAreaFilled(false);
        backgroundpanel.add(myprofile);
        myprofile.setBounds(0, 560, 180, 43);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        backgroundpanel.add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        navigation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        navigation.setForeground(new java.awt.Color(81, 162, 255));
        navigation.setText("NAVIGATION");
        backgroundpanel.add(navigation);
        navigation.setBounds(20, 180, 70, 16);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        backgroundpanel.add(signout);
        signout.setBounds(0, 780, 170, 43);

        backtoprofile.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        backtoprofile.setForeground(new java.awt.Color(81, 162, 255));
        backtoprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        backtoprofile.setText("Back to Profile");
        backtoprofile.setBorderPainted(false);
        backtoprofile.setContentAreaFilled(false);
        backtoprofile.addActionListener(this::backtoprofileActionPerformed);
        backgroundpanel.add(backtoprofile);
        backtoprofile.setBounds(280, 80, 130, 31);

        changepassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        changepassword.setText("Change Password");
        backgroundpanel.add(changepassword);
        changepassword.setBounds(310, 110, 160, 25);

        updatepassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        updatepassword.setForeground(new java.awt.Color(153, 161, 175));
        updatepassword.setText("Update your password to keep your account secure");
        backgroundpanel.add(updatepassword);
        updatepassword.setBounds(310, 130, 270, 30);

        resetpasswordpanel.setBackground(new java.awt.Color(255, 255, 255));
        resetpasswordpanel.setLayout(null);

        newpasswordlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newpasswordlabel.setText("New password");
        resetpasswordpanel.add(newpasswordlabel);
        newpasswordlabel.setBounds(30, 190, 110, 20);

        newpasswordtext.addActionListener(this::newpasswordtextActionPerformed);
        resetpasswordpanel.add(newpasswordtext);
        newpasswordtext.setBounds(30, 210, 440, 40);

        confirmnewpasswordlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmnewpasswordlabel.setText("Confirm New Password");
        resetpasswordpanel.add(confirmnewpasswordlabel);
        confirmnewpasswordlabel.setBounds(30, 270, 160, 20);

        confirmnewpasswordtext.addActionListener(this::confirmnewpasswordtextActionPerformed);
        resetpasswordpanel.add(confirmnewpasswordtext);
        confirmnewpasswordtext.setBounds(30, 290, 440, 40);

        updatepasswordbutton.setBackground(new java.awt.Color(47, 91, 255));
        updatepasswordbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatepasswordbutton.setForeground(new java.awt.Color(255, 255, 255));
        updatepasswordbutton.setText("Update Password");
        updatepasswordbutton.addActionListener(this::updatepasswordbuttonActionPerformed);
        resetpasswordpanel.add(updatepasswordbutton);
        updatepasswordbutton.setBounds(30, 380, 440, 40);

        currentpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        currentpassword.setText("Current Password");
        resetpasswordpanel.add(currentpassword);
        currentpassword.setBounds(30, 110, 130, 20);
        resetpasswordpanel.add(currentpasswordtext);
        currentpasswordtext.setBounds(30, 130, 440, 40);

        info.setBackground(new java.awt.Color(204, 255, 255));
        info.setLayout(null);

        desc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/additionalinfo.png"))); // NOI18N
        desc.setText("Make sure your new password is strong and easy to remember");
        info.add(desc);
        desc.setBounds(10, 6, 430, 30);

        resetpasswordpanel.add(info);
        info.setBounds(30, 20, 440, 40);

        backgroundpanel.add(resetpasswordpanel);
        resetpasswordpanel.setBounds(690, 240, 500, 480);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void backtoprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backtoprofileActionPerformed

    private void newpasswordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordtextActionPerformed

    private void confirmnewpasswordtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmnewpasswordtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmnewpasswordtextActionPerformed

    private void updatepasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepasswordbuttonActionPerformed
        
    }//GEN-LAST:event_updatepasswordbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChangePassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JButton backtoprofile;
    private javax.swing.JLabel changepassword;
    private javax.swing.JLabel cityscape;
    private javax.swing.JLabel confirmnewpasswordlabel;
    private javax.swing.JTextField confirmnewpasswordtext;
    private javax.swing.JLabel currentpassword;
    private javax.swing.JTextField currentpasswordtext;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel desc;
    private javax.swing.JPanel info;
    private javax.swing.JButton mealroutine;
    private javax.swing.JButton mycomplaints;
    private javax.swing.JButton myprofile;
    private javax.swing.JLabel navigation;
    private javax.swing.JLabel newpasswordlabel;
    private javax.swing.JTextField newpasswordtext;
    private javax.swing.JButton notice;
    private javax.swing.JButton notification;
    private javax.swing.JButton profile;
    private javax.swing.JPanel resetpasswordpanel;
    private javax.swing.JButton roomdetails;
    private javax.swing.JButton signout;
    private javax.swing.JLabel studentportal;
    private javax.swing.JLabel updatepassword;
    private javax.swing.JButton updatepasswordbutton;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables
public void UpdatePasswordListener(java.awt.event.ActionListener listener) {
    updatepasswordbutton.addActionListener(listener);
}
public void DashboardListener(java.awt.event.ActionListener listener) {
    dashboard.addActionListener(listener);
}

public void MyComplaintsListener(java.awt.event.ActionListener listener) {
    mycomplaints.addActionListener(listener);
}

public void MealRoutineListener(java.awt.event.ActionListener listener) {
    mealroutine.addActionListener(listener);
}

public void NoticeListener(java.awt.event.ActionListener listener) {
    notice.addActionListener(listener);
}

public void RoomDetailsListener(java.awt.event.ActionListener listener) {
    roomdetails.addActionListener(listener);
}

public void MyProfileListener(java.awt.event.ActionListener listener) {
    myprofile.addActionListener(listener);
}

public void SignOutListener(java.awt.event.ActionListener listener) {
    signout.addActionListener(listener);
}

public void NotificatinListener(java.awt.event.ActionListener listener) {
    notification.addActionListener(listener);
}

public void ProfileListener(java.awt.event.ActionListener listener) {
    profile.addActionListener(listener);
}

public void BackToProfileListener(java.awt.event.ActionListener listener) {
    backtoprofile.addActionListener(listener);
}

public void setWelcomeUser(String username) {
    welcomeback.setText("Welcome back, " + username + "!");
}

public javax.swing.JTextField getCurrentPasswordField() {
     return currentpasswordtext ;
}

public javax.swing.JTextField getNewPasswordField() {
    return newpasswordtext;
}

public javax.swing.JTextField getConfirmNewPasswordField() {
    return confirmnewpasswordtext;
}
}
