/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SkyLine Computer
 */
public class IssueComplaints extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueComplaints.class.getName());

    /**
     * Creates new form IssueComplaints
     */
    public IssueComplaints() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        CityScape = new javax.swing.JLabel();
        Administration = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        MyComplaints = new javax.swing.JButton();
        MealRoutine = new javax.swing.JButton();
        Notice = new javax.swing.JButton();
        RoomDetails = new javax.swing.JButton();
        Myprofile = new javax.swing.JButton();
        makepayment = new javax.swing.JButton();
        paymenthistory = new javax.swing.JButton();
        SignOut = new javax.swing.JButton();
        Card1 = new javax.swing.JPanel();
        Totalcomplaintscount = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Card2 = new javax.swing.JPanel();
        Pendingcount = new javax.swing.JLabel();
        Pending = new javax.swing.JLabel();
        Card3 = new javax.swing.JPanel();
        Resolvedcount = new javax.swing.JLabel();
        Resolved = new javax.swing.JLabel();
        Mycomplaints = new javax.swing.JLabel();
        Trackandmanageyourhostelcomplaints = new javax.swing.JLabel();
        Newcomplaint = new javax.swing.JButton();
        studentportal = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        complaintsscrollpanel = new javax.swing.JScrollPane();
        complaintpanel = new javax.swing.JPanel();
        particularcomplaintpanel = new javax.swing.JPanel();
        noticetitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateofissue = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        priority = new javax.swing.JLabel();
        buttonpanel = new javax.swing.JPanel();
        pendingbtn = new javax.swing.JButton();
        resolvedbtn = new javax.swing.JButton();
        allbtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        CityScape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CityScape.setForeground(new java.awt.Color(255, 255, 255));
        CityScape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        CityScape.setText("Cityscape");
        backgroundpanel.add(CityScape);
        CityScape.setBounds(20, 10, 170, 36);

        Administration.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Administration.setForeground(new java.awt.Color(81, 162, 255));
        Administration.setText("NAVIGATION");
        backgroundpanel.add(Administration);
        Administration.setBounds(20, 180, 70, 16);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        backgroundpanel.add(Dashboard);
        Dashboard.setBounds(-40, 210, 260, 43);

        MyComplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MyComplaints.setForeground(new java.awt.Color(255, 255, 255));
        MyComplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my complaints.png"))); // NOI18N
        MyComplaints.setText("My complaints");
        MyComplaints.setBorderPainted(false);
        MyComplaints.setContentAreaFilled(false);
        backgroundpanel.add(MyComplaints);
        MyComplaints.setBounds(-20, 280, 250, 43);

        MealRoutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MealRoutine.setForeground(new java.awt.Color(255, 255, 255));
        MealRoutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meal routine.png"))); // NOI18N
        MealRoutine.setText("Meal Routine");
        MealRoutine.setBorderPainted(false);
        MealRoutine.setContentAreaFilled(false);
        backgroundpanel.add(MealRoutine);
        MealRoutine.setBounds(-30, 350, 260, 43);

        Notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Notice.setForeground(new java.awt.Color(255, 255, 255));
        Notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notice.png"))); // NOI18N
        Notice.setText("Notice");
        Notice.setBorderPainted(false);
        Notice.setContentAreaFilled(false);
        backgroundpanel.add(Notice);
        Notice.setBounds(-20, 420, 190, 43);

        RoomDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoomDetails.setForeground(new java.awt.Color(255, 255, 255));
        RoomDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomdetails.png"))); // NOI18N
        RoomDetails.setText("Room Details");
        RoomDetails.setBorderPainted(false);
        RoomDetails.setContentAreaFilled(false);
        backgroundpanel.add(RoomDetails);
        RoomDetails.setBounds(-20, 480, 250, 43);

        Myprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Myprofile.setForeground(new java.awt.Color(255, 255, 255));
        Myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/myprofile.png"))); // NOI18N
        Myprofile.setText("My Profile");
        Myprofile.setBorderPainted(false);
        Myprofile.setContentAreaFilled(false);
        backgroundpanel.add(Myprofile);
        Myprofile.setBounds(0, 660, 170, 43);

        makepayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makepayment.setForeground(new java.awt.Color(255, 255, 255));
        makepayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/makepayment.png"))); // NOI18N
        makepayment.setText("Make Payment");
        makepayment.setBorderPainted(false);
        makepayment.setContentAreaFilled(false);
        backgroundpanel.add(makepayment);
        makepayment.setBounds(-30, 540, 270, 43);

        paymenthistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymenthistory.setForeground(new java.awt.Color(255, 255, 255));
        paymenthistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paymenthistory.png"))); // NOI18N
        paymenthistory.setText("Payment History");
        paymenthistory.setBorderPainted(false);
        paymenthistory.setContentAreaFilled(false);
        backgroundpanel.add(paymenthistory);
        paymenthistory.setBounds(-30, 600, 280, 43);

        SignOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign out.png"))); // NOI18N
        SignOut.setText("Sign Out");
        SignOut.setBorderPainted(false);
        SignOut.setContentAreaFilled(false);
        backgroundpanel.add(SignOut);
        SignOut.setBounds(0, 780, 190, 43);

        Card1.setBackground(new java.awt.Color(255, 255, 255));
        Card1.setLayout(null);

        Totalcomplaintscount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Totalcomplaintscount.setForeground(new java.awt.Color(102, 102, 255));
        Totalcomplaintscount.setText("5");
        Card1.add(Totalcomplaintscount);
        Totalcomplaintscount.setBounds(130, 10, 70, 30);

        Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(153, 161, 175));
        Total.setText("Total");
        Card1.add(Total);
        Total.setBounds(120, 40, 70, 40);

        backgroundpanel.add(Card1);
        Card1.setBounds(300, 190, 340, 80);

        Card2.setBackground(new java.awt.Color(255, 255, 255));
        Card2.setLayout(null);

        Pendingcount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Pendingcount.setForeground(new java.awt.Color(255, 153, 51));
        Pendingcount.setText("1");
        Card2.add(Pendingcount);
        Pendingcount.setBounds(130, 10, 60, 40);

        Pending.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pending.setForeground(new java.awt.Color(153, 161, 175));
        Pending.setText("Pending");
        Card2.add(Pending);
        Pending.setBounds(110, 40, 140, 40);

        backgroundpanel.add(Card2);
        Card2.setBounds(770, 190, 300, 80);

        Card3.setBackground(new java.awt.Color(255, 255, 255));
        Card3.setLayout(null);

        Resolvedcount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Resolvedcount.setForeground(new java.awt.Color(0, 153, 51));
        Resolvedcount.setText("5");
        Card3.add(Resolvedcount);
        Resolvedcount.setBounds(130, 20, 60, 30);

        Resolved.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Resolved.setForeground(new java.awt.Color(153, 161, 175));
        Resolved.setText("Resolved");
        Card3.add(Resolved);
        Resolved.setBounds(110, 50, 120, 25);

        backgroundpanel.add(Card3);
        Card3.setBounds(1200, 190, 310, 80);

        Mycomplaints.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Mycomplaints.setText("My Complaints");
        backgroundpanel.add(Mycomplaints);
        Mycomplaints.setBounds(300, 120, 190, 40);

        Trackandmanageyourhostelcomplaints.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Trackandmanageyourhostelcomplaints.setForeground(new java.awt.Color(153, 161, 175));
        Trackandmanageyourhostelcomplaints.setText("Track and manage your hostel complaints");
        backgroundpanel.add(Trackandmanageyourhostelcomplaints);
        Trackandmanageyourhostelcomplaints.setBounds(300, 160, 290, 20);

        Newcomplaint.setBackground(new java.awt.Color(30, 56, 168));
        Newcomplaint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Newcomplaint.setForeground(new java.awt.Color(255, 255, 255));
        Newcomplaint.setText("+ New Complaint");
        backgroundpanel.add(Newcomplaint);
        Newcomplaint.setBounds(1350, 140, 160, 30);

        studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentportal.setText("Student Portal");
        backgroundpanel.add(studentportal);
        studentportal.setBounds(300, 0, 170, 30);

        welcomeback.setText("Welcome Back");
        backgroundpanel.add(welcomeback);
        welcomeback.setBounds(300, 30, 250, 16);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        backgroundpanel.add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        backgroundpanel.add(profile);
        profile.setBounds(1480, 10, 41, 40);

        complaintpanel.setBackground(new java.awt.Color(255, 255, 255));
        complaintpanel.setLayout(null);

        particularcomplaintpanel.setLayout(null);

        noticetitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noticetitle.setText("Hostel Fee Payment Deadline ");
        particularcomplaintpanel.add(noticetitle);
        noticetitle.setBounds(20, 10, 250, 16);

        jLabel2.setText("All hostel residents are reminded that the hostel fee for May 2025 must be paid by May 15, 2025. Late payments will incur a penalty of ₹500 per week.");
        particularcomplaintpanel.add(jLabel2);
        jLabel2.setBounds(20, 30, 1000, 16);

        dateofissue.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dateofissue.setText("Apr 28, 2025 ");
        particularcomplaintpanel.add(dateofissue);
        dateofissue.setBounds(20, 60, 100, 14);

        category.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        category.setText("Finance");
        particularcomplaintpanel.add(category);
        category.setBounds(120, 60, 80, 14);

        priority.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        priority.setText("Urgent");
        particularcomplaintpanel.add(priority);
        priority.setBounds(220, 60, 60, 14);

        complaintpanel.add(particularcomplaintpanel);
        particularcomplaintpanel.setBounds(30, 60, 1130, 80);

        buttonpanel.setLayout(null);

        pendingbtn.setText("Pending");
        buttonpanel.add(pendingbtn);
        pendingbtn.setBounds(104, 0, 90, 30);

        resolvedbtn.setText("Resolved");
        buttonpanel.add(resolvedbtn);
        resolvedbtn.setBounds(220, 0, 90, 30);

        allbtn.setText("All");
        buttonpanel.add(allbtn);
        allbtn.setBounds(0, 0, 80, 30);

        complaintpanel.add(buttonpanel);
        buttonpanel.setBounds(850, 10, 310, 30);

        complaintsscrollpanel.setViewportView(complaintpanel);

        backgroundpanel.add(complaintsscrollpanel);
        complaintsscrollpanel.setBounds(300, 310, 1210, 490);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        backgroundpanel.add(Background);
        Background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueComplaints().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administration;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Card1;
    private javax.swing.JPanel Card2;
    private javax.swing.JPanel Card3;
    private javax.swing.JLabel CityScape;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton MealRoutine;
    private javax.swing.JButton MyComplaints;
    private javax.swing.JLabel Mycomplaints;
    private javax.swing.JButton Myprofile;
    private javax.swing.JButton Newcomplaint;
    private javax.swing.JButton Notice;
    private javax.swing.JLabel Pending;
    private javax.swing.JLabel Pendingcount;
    private javax.swing.JLabel Resolved;
    private javax.swing.JLabel Resolvedcount;
    private javax.swing.JButton RoomDetails;
    private javax.swing.JButton SignOut;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Totalcomplaintscount;
    private javax.swing.JLabel Trackandmanageyourhostelcomplaints;
    private javax.swing.JButton allbtn;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JLabel category;
    private javax.swing.JPanel complaintpanel;
    private javax.swing.JScrollPane complaintsscrollpanel;
    private javax.swing.JLabel dateofissue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton makepayment;
    private javax.swing.JLabel noticetitle;
    private javax.swing.JButton notification;
    private javax.swing.JPanel particularcomplaintpanel;
    private javax.swing.JButton paymenthistory;
    private javax.swing.JButton pendingbtn;
    private javax.swing.JLabel priority;
    private javax.swing.JButton profile;
    private javax.swing.JButton resolvedbtn;
    private javax.swing.JLabel studentportal;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables

public void setWelcomeUser(String username)     { welcomeback.setText("Welcome Back, " + username+ "!"); }
public void setTotalComplaints(int n)           { Totalcomplaintscount.setText(String.valueOf(n)); }
public void setPendingCount(int n)              { Pendingcount.setText(String.valueOf(n)); }
public void setResolvedCount(int n)             { Resolvedcount.setText(String.valueOf(n)); }
 
public javax.swing.JPanel getComplaintPanel()   { return complaintpanel; }
 
public void NewComplaintListener(java.awt.event.ActionListener l)  { Newcomplaint.addActionListener(l); }
public void AllListener(java.awt.event.ActionListener l)           { allbtn.addActionListener(l); }
public void PendingListener(java.awt.event.ActionListener l)       { pendingbtn.addActionListener(l); }
public void ResolvedListener(java.awt.event.ActionListener l)      { resolvedbtn.addActionListener(l); }
public void DashboardListener(java.awt.event.ActionListener l)     { Dashboard.addActionListener(l); }
public void NoticeListener(java.awt.event.ActionListener l)        { Notice.addActionListener(l); }
public void MyProfileListener(java.awt.event.ActionListener l)     { Myprofile.addActionListener(l); }
public void SignOutListener(java.awt.event.ActionListener l)       { SignOut.addActionListener(l); }
public void ProfileListener(java.awt.event.ActionListener l)       { profile.addActionListener(l); }
public void RoomDetailsListener(java.awt.event.ActionListener listener) {
    RoomDetails.addActionListener(listener);
}
public void MakePaymentListener(java.awt.event.ActionListener listener) {
    makepayment.addActionListener(listener);
}

public void PaymentHistoryListener(java.awt.event.ActionListener listener) {
    paymenthistory.addActionListener(listener);
}

public void MealRoutineListener(java.awt.event.ActionListener listener) {
    MealRoutine.addActionListener(listener);
}
}
