/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SkyLine Computer
 */
public class IssueComplaints extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueComplaints.class.getName());

    /**
     * Creates new form IssueComplaints
     */
    public IssueComplaints() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        CityScape = new javax.swing.JLabel();
        Administration = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        MyComplaints = new javax.swing.JButton();
        MealRoutine = new javax.swing.JButton();
        Notice = new javax.swing.JButton();
        RoomDetails = new javax.swing.JButton();
        Myprofile = new javax.swing.JButton();
        SignOut = new javax.swing.JButton();
        Card1 = new javax.swing.JPanel();
        Totalcomplaintscount = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Card2 = new javax.swing.JPanel();
        Pendingcount = new javax.swing.JLabel();
        Pending = new javax.swing.JLabel();
        Card3 = new javax.swing.JPanel();
        Inprogresscount = new javax.swing.JLabel();
        Inprogress = new javax.swing.JLabel();
        Card4 = new javax.swing.JPanel();
        Resolvedcount = new javax.swing.JLabel();
        Resolved = new javax.swing.JLabel();
        Mycomplaints = new javax.swing.JLabel();
        Trackandmanageyourhostelcomplaints = new javax.swing.JLabel();
        Newcomplaint = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        CityScape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CityScape.setForeground(new java.awt.Color(255, 255, 255));
        CityScape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        CityScape.setText("Cityscape");
        backgroundpanel.add(CityScape);
        CityScape.setBounds(20, 20, 170, 36);

        Administration.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Administration.setForeground(new java.awt.Color(194, 122, 255));
        Administration.setText("Administration");
        backgroundpanel.add(Administration);
        Administration.setBounds(20, 180, 70, 16);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard.png"))); // NOI18N
        Dashboard.setText("Dashboard");
        Dashboard.setContentAreaFilled(false);
        backgroundpanel.add(Dashboard);
        Dashboard.setBounds(10, 210, 160, 43);

        MyComplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MyComplaints.setForeground(new java.awt.Color(255, 255, 255));
        MyComplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/my complaints.png"))); // NOI18N
        MyComplaints.setText("My complaints");
        MyComplaints.setContentAreaFilled(false);
        backgroundpanel.add(MyComplaints);
        MyComplaints.setBounds(10, 280, 190, 43);

        MealRoutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MealRoutine.setForeground(new java.awt.Color(255, 255, 255));
        MealRoutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/meal routine.png"))); // NOI18N
        MealRoutine.setText("Meal Routine");
        MealRoutine.setContentAreaFilled(false);
        backgroundpanel.add(MealRoutine);
        MealRoutine.setBounds(10, 350, 180, 43);

        Notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Notice.setForeground(new java.awt.Color(255, 255, 255));
        Notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notice.png"))); // NOI18N
        Notice.setText("Notice");
        Notice.setContentAreaFilled(false);
        backgroundpanel.add(Notice);
        Notice.setBounds(-10, 480, 180, 43);

        RoomDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoomDetails.setForeground(new java.awt.Color(255, 255, 255));
        RoomDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomdetails.png"))); // NOI18N
        RoomDetails.setText("Room Details");
        RoomDetails.setContentAreaFilled(false);
        backgroundpanel.add(RoomDetails);
        RoomDetails.setBounds(10, 420, 190, 43);

        Myprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Myprofile.setForeground(new java.awt.Color(255, 255, 255));
        Myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/myprofile.png"))); // NOI18N
        Myprofile.setText("My Profile");
        Myprofile.setContentAreaFilled(false);
        backgroundpanel.add(Myprofile);
        Myprofile.setBounds(10, 540, 170, 43);

        SignOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sign out.png"))); // NOI18N
        SignOut.setText("Sign Out");
        SignOut.setContentAreaFilled(false);
        backgroundpanel.add(SignOut);
        SignOut.setBounds(10, 610, 190, 43);

        Card1.setBackground(new java.awt.Color(255, 255, 255));
        Card1.setLayout(null);

        Totalcomplaintscount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Totalcomplaintscount.setForeground(new java.awt.Color(102, 102, 255));
        Totalcomplaintscount.setText("5");
        Card1.add(Totalcomplaintscount);
        Totalcomplaintscount.setBounds(100, 30, 30, 30);

        Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(153, 161, 175));
        Total.setText("Total");
        Card1.add(Total);
        Total.setBounds(90, 70, 40, 16);

        backgroundpanel.add(Card1);
        Card1.setBounds(320, 190, 250, 100);

        Card2.setBackground(new java.awt.Color(255, 255, 255));
        Card2.setLayout(null);

        Pendingcount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Pendingcount.setForeground(new java.awt.Color(255, 153, 51));
        Pendingcount.setText("1");
        Card2.add(Pendingcount);
        Pendingcount.setBounds(120, 30, 12, 40);

        Pending.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pending.setForeground(new java.awt.Color(153, 161, 175));
        Pending.setText("Pending");
        Card2.add(Pending);
        Pending.setBounds(90, 60, 80, 30);

        backgroundpanel.add(Card2);
        Card2.setBounds(620, 190, 250, 99);

        Card3.setBackground(new java.awt.Color(255, 255, 255));
        Card3.setLayout(null);

        Inprogresscount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Inprogresscount.setForeground(new java.awt.Color(51, 51, 255));
        Inprogresscount.setText("1");
        Card3.add(Inprogresscount);
        Inprogresscount.setBounds(110, 36, 37, 30);

        Inprogress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Inprogress.setForeground(new java.awt.Color(153, 161, 175));
        Inprogress.setText("In Progress");
        Card3.add(Inprogress);
        Inprogress.setBounds(70, 60, 110, 30);

        backgroundpanel.add(Card3);
        Card3.setBounds(920, 190, 250, 100);

        Card4.setBackground(new java.awt.Color(255, 255, 255));
        Card4.setLayout(null);

        Resolvedcount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Resolvedcount.setForeground(new java.awt.Color(0, 153, 51));
        Resolvedcount.setText("5");
        Card4.add(Resolvedcount);
        Resolvedcount.setBounds(100, 40, 20, 20);

        Resolved.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Resolved.setForeground(new java.awt.Color(153, 161, 175));
        Resolved.setText("Resolved");
        Card4.add(Resolved);
        Resolved.setBounds(80, 60, 90, 25);

        backgroundpanel.add(Card4);
        Card4.setBounds(1230, 190, 250, 100);

        Mycomplaints.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Mycomplaints.setText("My Complaints");
        backgroundpanel.add(Mycomplaints);
        Mycomplaints.setBounds(300, 120, 190, 40);

        Trackandmanageyourhostelcomplaints.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Trackandmanageyourhostelcomplaints.setForeground(new java.awt.Color(153, 161, 175));
        Trackandmanageyourhostelcomplaints.setText("Track and manage your hostel complaints");
        backgroundpanel.add(Trackandmanageyourhostelcomplaints);
        Trackandmanageyourhostelcomplaints.setBounds(300, 160, 290, 20);

        Newcomplaint.setBackground(new java.awt.Color(30, 56, 168));
        Newcomplaint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Newcomplaint.setForeground(new java.awt.Color(255, 255, 255));
        Newcomplaint.setText("+ New Complaint");
        backgroundpanel.add(Newcomplaint);
        Newcomplaint.setBounds(1340, 143, 140, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/adminbackground.png"))); // NOI18N
        Background.setText("jLabel1");
        backgroundpanel.add(Background);
        Background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueComplaints().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administration;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Card1;
    private javax.swing.JPanel Card2;
    private javax.swing.JPanel Card3;
    private javax.swing.JPanel Card4;
    private javax.swing.JLabel CityScape;
    private javax.swing.JButton Dashboard;
    private javax.swing.JLabel Inprogress;
    private javax.swing.JLabel Inprogresscount;
    private javax.swing.JButton MealRoutine;
    private javax.swing.JButton MyComplaints;
    private javax.swing.JLabel Mycomplaints;
    private javax.swing.JButton Myprofile;
    private javax.swing.JButton Newcomplaint;
    private javax.swing.JButton Notice;
    private javax.swing.JLabel Pending;
    private javax.swing.JLabel Pendingcount;
    private javax.swing.JLabel Resolved;
    private javax.swing.JLabel Resolvedcount;
    private javax.swing.JButton RoomDetails;
    private javax.swing.JButton SignOut;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Totalcomplaintscount;
    private javax.swing.JLabel Trackandmanageyourhostelcomplaints;
    private javax.swing.JPanel backgroundpanel;
    // End of variables declaration//GEN-END:variables
}
