/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class IssueNotice extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueNotice.class.getName());

    /**
     * Creates new form IssueNotice
     */
    public IssueNotice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issuenoticepanel = new javax.swing.JPanel();
        noticetitle = new javax.swing.JLabel();
        noticetitletext = new javax.swing.JTextField();
        category = new javax.swing.JLabel();
        categorycombobox = new javax.swing.JComboBox<>();
        Priority = new javax.swing.JLabel();
        prioritycombobox = new javax.swing.JComboBox<>();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        publishbutton = new javax.swing.JButton();
        pinnotice = new javax.swing.JCheckBox();
        cancelbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        issuenoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        issuenoticepanel.setLayout(null);

        noticetitle.setText("Notice Title");
        issuenoticepanel.add(noticetitle);
        noticetitle.setBounds(10, 10, 70, 16);
        issuenoticepanel.add(noticetitletext);
        noticetitletext.setBounds(10, 30, 330, 22);

        category.setText("Category");
        issuenoticepanel.add(category);
        category.setBounds(10, 160, 60, 16);

        categorycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finance", "Management", "Event", "Meal" }));
        categorycombobox.addActionListener(this::categorycomboboxActionPerformed);
        issuenoticepanel.add(categorycombobox);
        categorycombobox.setBounds(10, 180, 140, 22);

        Priority.setText("Priority");
        issuenoticepanel.add(Priority);
        Priority.setBounds(190, 160, 50, 16);

        prioritycombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "High", "Normal" }));
        issuenoticepanel.add(prioritycombobox);
        prioritycombobox.setBounds(190, 180, 150, 22);

        description.setText("Description");
        issuenoticepanel.add(description);
        description.setBounds(10, 70, 70, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        issuenoticepanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 330, 50);

        publishbutton.setBackground(new java.awt.Color(99, 102, 255));
        publishbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        publishbutton.setForeground(new java.awt.Color(255, 255, 255));
        publishbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/publish.png"))); // NOI18N
        publishbutton.setText("Publish");
        publishbutton.addActionListener(this::publishbuttonActionPerformed);
        issuenoticepanel.add(publishbutton);
        publishbutton.setBounds(190, 260, 150, 30);

        pinnotice.setText("Pin Notice");
        pinnotice.addActionListener(this::pinnoticeActionPerformed);
        issuenoticepanel.add(pinnotice);
        pinnotice.setBounds(10, 230, 130, 20);

        cancelbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelbutton.setText("Cancel");
        issuenoticepanel.add(cancelbutton);
        cancelbutton.setBounds(10, 260, 150, 30);

        getContentPane().add(issuenoticepanel);
        issuenoticepanel.setBounds(0, 0, 350, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinnoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinnoticeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinnoticeActionPerformed

    private void categorycomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorycomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorycomboboxActionPerformed

    private void publishbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publishbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueNotice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Priority;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JLabel category;
    private javax.swing.JComboBox<String> categorycombobox;
    private javax.swing.JLabel description;
    private javax.swing.JPanel issuenoticepanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel noticetitle;
    private javax.swing.JTextField noticetitletext;
    private javax.swing.JCheckBox pinnotice;
    private javax.swing.JComboBox<String> prioritycombobox;
    private javax.swing.JButton publishbutton;
    // End of variables declaration//GEN-END:variables


// ── Field / component accessors ───────────────────────────────────────────────
public javax.swing.JTextField getTitleField() {
    return noticetitletext;
}

public javax.swing.JTextArea getDescriptionArea() {
    return jTextArea1;
}

public javax.swing.JComboBox<String> getCategoryCombo() {
    return categorycombobox;
}

public javax.swing.JComboBox<String> getPriorityCombo() {
    return prioritycombobox;
}

public boolean isPinned() {
    return pinnotice.isSelected();
}

// ── Button listeners ─────────────────────────────────────────────────────────
public void PublishListener(java.awt.event.ActionListener listener) {
    publishbutton.addActionListener(listener);
}

public void CancelListener(java.awt.event.ActionListener listener) {
    cancelbutton.addActionListener(listener);
}
}
