/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class IssueNotice extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueNotice.class.getName());

    /**
     * Creates new form ViewStudentDetails
     */
    public IssueNotice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admindashboard = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        administration = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        complaints = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        roomallocation = new javax.swing.JButton();
        adminprofile = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        noticemanagement = new javax.swing.JLabel();
        noticedesc = new javax.swing.JLabel();
        issuenoticepanel = new javax.swing.JPanel();
        noticetitle = new javax.swing.JLabel();
        noticetitletext = new javax.swing.JTextField();
        category = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Priority = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        publishbutton = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        noticelist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backgroundpanel = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        admindashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        admindashboard.setText("Admin Dashboard");
        getContentPane().add(admindashboard);
        admindashboard.setBounds(300, 0, 220, 30);

        welcomeback.setText("Welcome Back");
        getContentPane().add(welcomeback);
        welcomeback.setBounds(340, 30, 90, 16);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        getContentPane().add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        getContentPane().add(profile);
        profile.setBounds(1480, 10, 41, 40);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        getContentPane().add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        administration.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        administration.setForeground(new java.awt.Color(194, 122, 255));
        administration.setText("ADMINISTRATION");
        getContentPane().add(administration);
        administration.setBounds(20, 180, 90, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        getContentPane().add(dashboard);
        dashboard.setBounds(10, 210, 160, 43);

        complaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        complaints.setForeground(new java.awt.Color(255, 255, 255));
        complaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/my complaints.png"))); // NOI18N
        complaints.setText("Complaints");
        complaints.setBorderPainted(false);
        complaints.setContentAreaFilled(false);
        getContentPane().add(complaints);
        complaints.setBounds(-10, 280, 200, 43);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        getContentPane().add(mealroutine);
        mealroutine.setBounds(10, 350, 180, 43);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        getContentPane().add(notice);
        notice.setBounds(0, 420, 140, 43);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        roomdetails.addActionListener(this::roomdetailsActionPerformed);
        getContentPane().add(roomdetails);
        roomdetails.setBounds(0, 490, 200, 43);

        roomallocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomallocation.setForeground(new java.awt.Color(255, 255, 255));
        roomallocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomallocation.png"))); // NOI18N
        roomallocation.setText("Room Allocation");
        roomallocation.setBorderPainted(false);
        roomallocation.setContentAreaFilled(false);
        roomallocation.addActionListener(this::roomallocationActionPerformed);
        getContentPane().add(roomallocation);
        roomallocation.setBounds(0, 560, 230, 43);

        adminprofile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminprofile.setForeground(new java.awt.Color(255, 255, 255));
        adminprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/myprofile.png"))); // NOI18N
        adminprofile.setText("Admin Profile");
        adminprofile.setBorderPainted(false);
        adminprofile.setContentAreaFilled(false);
        getContentPane().add(adminprofile);
        adminprofile.setBounds(0, 630, 180, 43);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        getContentPane().add(signout);
        signout.setBounds(0, 780, 170, 43);

        noticemanagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noticemanagement.setText("Notice Management");
        getContentPane().add(noticemanagement);
        noticemanagement.setBounds(310, 90, 180, 25);

        noticedesc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        noticedesc.setForeground(new java.awt.Color(153, 161, 175));
        noticedesc.setText("Create and manage hostel announcements");
        getContentPane().add(noticedesc);
        noticedesc.setBounds(310, 110, 270, 30);

        issuenoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        issuenoticepanel.setLayout(null);

        noticetitle.setText("Notice Title");
        issuenoticepanel.add(noticetitle);
        noticetitle.setBounds(10, 10, 70, 16);
        issuenoticepanel.add(noticetitletext);
        noticetitletext.setBounds(10, 30, 270, 22);

        category.setText("Category");
        issuenoticepanel.add(category);
        category.setBounds(470, 10, 60, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finance", "Management", "Event", "Meal" }));
        issuenoticepanel.add(jComboBox1);
        jComboBox1.setBounds(470, 30, 280, 22);

        Priority.setText("Priority");
        issuenoticepanel.add(Priority);
        Priority.setBounds(910, 10, 50, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgent", "High", "Normal", " " }));
        issuenoticepanel.add(jComboBox2);
        jComboBox2.setBounds(910, 30, 280, 22);

        description.setText("Description");
        issuenoticepanel.add(description);
        description.setBounds(10, 80, 70, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        issuenoticepanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 1180, 50);

        publishbutton.setBackground(new java.awt.Color(99, 102, 255));
        publishbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/publish.png"))); // NOI18N
        publishbutton.setText("Publish");
        issuenoticepanel.add(publishbutton);
        publishbutton.setBounds(1090, 170, 103, 20);

        jCheckBox1.setText("Pin Notice");
        issuenoticepanel.add(jCheckBox1);
        jCheckBox1.setBounds(10, 170, 77, 20);

        getContentPane().add(issuenoticepanel);
        issuenoticepanel.setBounds(310, 160, 1210, 200);

        noticelist.setBackground(new java.awt.Color(255, 255, 255));
        noticelist.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title ", "Category ", "Priority", "Date Posted", "Action"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        noticelist.add(jScrollPane2);
        jScrollPane2.setBounds(11, 5, 1190, 390);

        getContentPane().add(noticelist);
        noticelist.setBounds(310, 410, 1210, 400);

        backgroundpanel.setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/adminbackground.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void roomdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomdetailsActionPerformed

    private void roomallocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomallocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomallocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueNotice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Priority;
    private javax.swing.JLabel admindashboard;
    private javax.swing.JLabel administration;
    private javax.swing.JButton adminprofile;
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel category;
    private javax.swing.JLabel cityscape;
    private javax.swing.JButton complaints;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel description;
    private javax.swing.JPanel issuenoticepanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mealroutine;
    private javax.swing.JButton notice;
    private javax.swing.JLabel noticedesc;
    private javax.swing.JPanel noticelist;
    private javax.swing.JLabel noticemanagement;
    private javax.swing.JLabel noticetitle;
    private javax.swing.JTextField noticetitletext;
    private javax.swing.JButton notification;
    private javax.swing.JButton profile;
    private javax.swing.JButton publishbutton;
    private javax.swing.JButton roomallocation;
    private javax.swing.JButton roomdetails;
    private javax.swing.JButton signout;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables
}
