/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sulav
 */
public class LogIn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn.class.getName());

    /**
     * Creates new form LogIN
     */
    public LogIn() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogIN = new javax.swing.JPanel();
        Password_data = new javax.swing.JPasswordField();
        Dont_have_acc = new javax.swing.JLabel();
        LOGIN = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Email_data = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        Text = new javax.swing.JLabel();
        forgetpasswordbutton = new javax.swing.JButton();
        Or = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        Username_data1 = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(1556, 0, 0, 0);

        LogIN.setBackground(new java.awt.Color(255, 255, 255));
        LogIN.setLayout(null);

        Password_data.setBackground(new java.awt.Color(171, 186, 255));
        Password_data.setText("8888888888");
        Password_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_dataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_dataFocusLost(evt);
            }
        });
        Password_data.addActionListener(this::Password_dataActionPerformed);
        LogIN.add(Password_data);
        Password_data.setBounds(20, 240, 516, 22);

        Dont_have_acc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dont_have_acc.setText("Don't have an account?");
        LogIN.add(Dont_have_acc);
        Dont_have_acc.setBounds(20, 380, 150, 20);

        LOGIN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LOGIN.setText("Log In");
        LogIN.add(LOGIN);
        LOGIN.setBounds(20, 33, 115, 25);

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setText("Email");
        LogIN.add(Email);
        Email.setBounds(20, 160, 87, 16);

        Email_data.setBackground(new java.awt.Color(171, 186, 255));
        Email_data.addActionListener(this::Email_dataActionPerformed);
        LogIN.add(Email_data);
        Email_data.setBounds(20, 180, 516, 20);

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setText("Password");
        LogIN.add(password);
        password.setBounds(20, 220, 75, 16);

        loginbutton.setBackground(new java.awt.Color(5, 13, 153));
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setText("Log In");
        loginbutton.addActionListener(this::loginbuttonActionPerformed);
        LogIN.add(loginbutton);
        loginbutton.setBounds(20, 340, 516, 23);

        registerbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(5, 13, 153));
        registerbutton.setText("Register here");
        registerbutton.setBorderPainted(false);
        registerbutton.setContentAreaFilled(false);
        registerbutton.addActionListener(this::registerbuttonActionPerformed);
        LogIN.add(registerbutton);
        registerbutton.setBounds(160, 370, 120, 40);

        Text.setText("Enter your credentials to access your dashboard");
        LogIN.add(Text);
        Text.setBounds(20, 64, 263, 16);

        forgetpasswordbutton.setForeground(new java.awt.Color(5, 13, 153));
        forgetpasswordbutton.setText("Forget password?");
        forgetpasswordbutton.setBorderPainted(false);
        forgetpasswordbutton.setContentAreaFilled(false);
        forgetpasswordbutton.addActionListener(this::forgetpasswordbuttonActionPerformed);
        LogIN.add(forgetpasswordbutton);
        forgetpasswordbutton.setBounds(400, 270, 140, 23);

        Or.setText("--------------------------------------------------------------- or -------------------------------------------------------------");
        LogIN.add(Or);
        Or.setBounds(20, 310, 516, 16);

        username1.setBackground(new java.awt.Color(0, 0, 0));
        username1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username1.setText("Username ");
        LogIN.add(username1);
        username1.setBounds(20, 98, 87, 16);

        Username_data1.setBackground(new java.awt.Color(171, 186, 255));
        Username_data1.addActionListener(this::Username_data1ActionPerformed);
        LogIN.add(Username_data1);
        Username_data1.setBounds(20, 120, 516, 20);

        getContentPane().add(LogIN);
        LogIN.setBounds(760, 180, 590, 540);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/WhatsApp Image 2026-05-20 at 5.01.07 PM.jpeg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Password_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_dataActionPerformed

    private void Email_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_dataActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void forgetpasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetpasswordbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetpasswordbuttonActionPerformed

    private void Username_data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_data1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_data1ActionPerformed

    private void Password_dataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_dataFocusGained
        if(Password_data.getText().equals("**********")){
            Password_data.setText(""); }       // TODO add your handling code here:
    }//GEN-LAST:event_Password_dataFocusGained

    private void Password_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_dataFocusLost
        if(Password_data.getText().equals("")){
            Password_data.setText("**********");// TODO add your handling code here:
    }//GEN-LAST:event_Password_dataFocusLost
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Dont_have_acc;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Email_data;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JPanel LogIN;
    private javax.swing.JLabel Or;
    private javax.swing.JPasswordField Password_data;
    private javax.swing.JLabel Text;
    private javax.swing.JTextField Username_data1;
    private javax.swing.JButton forgetpasswordbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel password;
    private javax.swing.JButton registerbutton;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables

// REPLACE these methods at the bottom of LogIn.java

public javax.swing.JTextField getEmailField() {
    return Email_data;
}

// FIXED: return JPasswordField, not JTextField
public javax.swing.JPasswordField getPasswordField() {
    return Password_data;
}

public javax.swing.JTextField getUsernameField() {
    return Username_data1;
}

public void LoginListener(java.awt.event.ActionListener listener) {
    loginbutton.addActionListener(listener);
}

public void SignupListener(java.awt.event.ActionListener listener) {
    registerbutton.addActionListener(listener);
}

public void ForgetPasswordListener(java.awt.event.ActionListener listener) {
    forgetpasswordbutton.addActionListener(listener);
}

}
