/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class NoticeAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NoticeAdmin.class.getName());

    /**
     * Creates new form ViewStudentDetails
     */
    public NoticeAdmin() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admindashboard = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        administration = new javax.swing.JLabel();
        notice = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        noticemanagement = new javax.swing.JLabel();
        noticedesc = new javax.swing.JLabel();
        newnotice = new javax.swing.JButton();
        roomallocation = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        dashboard = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        complaints = new javax.swing.JButton();
        pinnednoticepanel = new javax.swing.JPanel();
        pinnednotice = new javax.swing.JLabel();
        pinnednoticenumber = new javax.swing.JLabel();
        urgentnoticepanel = new javax.swing.JPanel();
        urgentnotice = new javax.swing.JLabel();
        urgentnoticenumber = new javax.swing.JLabel();
        totalnoticepanel = new javax.swing.JPanel();
        totalnotice = new javax.swing.JLabel();
        totalnumber = new javax.swing.JLabel();
        noticelist = new javax.swing.JPanel();
        allnoticescrollpane = new javax.swing.JScrollPane();
        allnoticepanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        deletenotice = new javax.swing.JButton();
        viewnotice = new javax.swing.JButton();
        adminprofile = new javax.swing.JButton();
        students = new javax.swing.JButton();
        backgroundpanel = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        admindashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        admindashboard.setText("Admin Dashboard");
        getContentPane().add(admindashboard);
        admindashboard.setBounds(300, 0, 220, 30);

        welcomeback.setText("Welcome Back");
        getContentPane().add(welcomeback);
        welcomeback.setBounds(340, 30, 90, 16);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        getContentPane().add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        getContentPane().add(profile);
        profile.setBounds(1480, 10, 41, 40);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        getContentPane().add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        administration.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        administration.setForeground(new java.awt.Color(194, 122, 255));
        administration.setText("ADMINISTRATION");
        getContentPane().add(administration);
        administration.setBounds(20, 180, 90, 16);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        getContentPane().add(notice);
        notice.setBounds(0, 420, 140, 43);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        getContentPane().add(signout);
        signout.setBounds(0, 780, 170, 43);

        noticemanagement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noticemanagement.setText("Notice Management");
        getContentPane().add(noticemanagement);
        noticemanagement.setBounds(310, 90, 180, 25);

        noticedesc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        noticedesc.setForeground(new java.awt.Color(153, 161, 175));
        noticedesc.setText("Create and manage hostel announcements");
        getContentPane().add(noticedesc);
        noticedesc.setBounds(310, 110, 270, 30);

        newnotice.setBackground(new java.awt.Color(99, 102, 255));
        newnotice.setForeground(new java.awt.Color(255, 255, 255));
        newnotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/addnotice.png"))); // NOI18N
        newnotice.setText("New Notice");
        getContentPane().add(newnotice);
        newnotice.setBounds(1375, 103, 140, 30);

        roomallocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomallocation.setForeground(new java.awt.Color(255, 255, 255));
        roomallocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomallocation.png"))); // NOI18N
        roomallocation.setText("Room Allocation");
        roomallocation.setBorderPainted(false);
        roomallocation.setContentAreaFilled(false);
        roomallocation.addActionListener(this::roomallocationActionPerformed);
        getContentPane().add(roomallocation);
        roomallocation.setBounds(-30, 560, 280, 43);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        roomdetails.addActionListener(this::roomdetailsActionPerformed);
        getContentPane().add(roomdetails);
        roomdetails.setBounds(-20, 490, 240, 43);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        getContentPane().add(dashboard);
        dashboard.setBounds(-50, 210, 280, 43);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        getContentPane().add(mealroutine);
        mealroutine.setBounds(-40, 350, 270, 43);

        complaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        complaints.setForeground(new java.awt.Color(255, 255, 255));
        complaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/my complaints.png"))); // NOI18N
        complaints.setText("Complaints");
        complaints.setBorderPainted(false);
        complaints.setContentAreaFilled(false);
        getContentPane().add(complaints);
        complaints.setBounds(-60, 280, 290, 43);

        pinnednoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        pinnednoticepanel.setLayout(null);

        pinnednotice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pinnednotice.setText("Pinned Notice");
        pinnednoticepanel.add(pinnednotice);
        pinnednotice.setBounds(10, 10, 300, 16);

        pinnednoticenumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pinnednoticenumber.setForeground(new java.awt.Color(249, 115, 22));
        pinnednoticenumber.setText("2");
        pinnednoticepanel.add(pinnednoticenumber);
        pinnednoticenumber.setBounds(10, 30, 140, 30);

        getContentPane().add(pinnednoticepanel);
        pinnednoticepanel.setBounds(720, 150, 390, 80);

        urgentnoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        urgentnoticepanel.setLayout(null);

        urgentnotice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        urgentnotice.setText("Urgent Notice");
        urgentnoticepanel.add(urgentnotice);
        urgentnotice.setBounds(10, 10, 300, 20);

        urgentnoticenumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        urgentnoticenumber.setForeground(new java.awt.Color(231, 0, 11));
        urgentnoticenumber.setText("2");
        urgentnoticepanel.add(urgentnoticenumber);
        urgentnoticenumber.setBounds(10, 30, 190, 30);

        getContentPane().add(urgentnoticepanel);
        urgentnoticepanel.setBounds(1140, 150, 380, 80);

        totalnoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        totalnoticepanel.setLayout(null);

        totalnotice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalnotice.setText("Total Notice");
        totalnoticepanel.add(totalnotice);
        totalnotice.setBounds(10, 10, 300, 20);

        totalnumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalnumber.setForeground(new java.awt.Color(99, 102, 255));
        totalnumber.setText("5");
        totalnoticepanel.add(totalnumber);
        totalnumber.setBounds(10, 30, 90, 30);

        getContentPane().add(totalnoticepanel);
        totalnoticepanel.setBounds(310, 150, 380, 80);

        noticelist.setBackground(new java.awt.Color(255, 255, 255));
        noticelist.setLayout(null);

        allnoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        allnoticepanel.setLayout(null);

        jPanel1.setLayout(null);

        deletenotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/deletenotice.png"))); // NOI18N
        jPanel1.add(deletenotice);
        deletenotice.setBounds(1090, 20, 50, 40);

        viewnotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/viewnotice.png"))); // NOI18N
        jPanel1.add(viewnotice);
        viewnotice.setBounds(1030, 20, 50, 40);

        allnoticepanel.add(jPanel1);
        jPanel1.setBounds(10, 20, 1150, 70);

        allnoticescrollpane.setViewportView(allnoticepanel);

        noticelist.add(allnoticescrollpane);
        allnoticescrollpane.setBounds(12, 20, 1180, 500);

        getContentPane().add(noticelist);
        noticelist.setBounds(310, 270, 1210, 540);

        adminprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminprofile.setForeground(new java.awt.Color(255, 255, 255));
        adminprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/myprofile.png"))); // NOI18N
        adminprofile.setText("Admin Profile");
        adminprofile.setBorderPainted(false);
        adminprofile.setContentAreaFilled(false);
        getContentPane().add(adminprofile);
        adminprofile.setBounds(-40, 680, 280, 43);

        students.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        students.setForeground(new java.awt.Color(255, 255, 255));
        students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/students.png"))); // NOI18N
        students.setText("Students");
        students.setBorderPainted(false);
        students.setContentAreaFilled(false);
        getContentPane().add(students);
        students.setBounds(-60, 620, 280, 43);

        backgroundpanel.setLayout(null);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/adminbackground.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void roomdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomdetailsActionPerformed

    private void roomallocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomallocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomallocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NoticeAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admindashboard;
    private javax.swing.JLabel administration;
    private javax.swing.JButton adminprofile;
    private javax.swing.JPanel allnoticepanel;
    private javax.swing.JScrollPane allnoticescrollpane;
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel cityscape;
    private javax.swing.JButton complaints;
    private javax.swing.JButton dashboard;
    private javax.swing.JButton deletenotice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mealroutine;
    private javax.swing.JButton newnotice;
    private javax.swing.JButton notice;
    private javax.swing.JLabel noticedesc;
    private javax.swing.JPanel noticelist;
    private javax.swing.JLabel noticemanagement;
    private javax.swing.JButton notification;
    private javax.swing.JLabel pinnednotice;
    private javax.swing.JLabel pinnednoticenumber;
    private javax.swing.JPanel pinnednoticepanel;
    private javax.swing.JButton profile;
    private javax.swing.JButton roomallocation;
    private javax.swing.JButton roomdetails;
    private javax.swing.JButton signout;
    private javax.swing.JButton students;
    private javax.swing.JLabel totalnotice;
    private javax.swing.JPanel totalnoticepanel;
    private javax.swing.JLabel totalnumber;
    private javax.swing.JLabel urgentnotice;
    private javax.swing.JLabel urgentnoticenumber;
    private javax.swing.JPanel urgentnoticepanel;
    private javax.swing.JButton viewnotice;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables


// ── Panel accessor (controller builds notice cards into this panel) ──────────
public javax.swing.JPanel getNoticeListPanel() {
    return allnoticepanel;
}

// ── Stats setters ─────────────────────────────────────────────────────────────
public void setTotalNotices(int count) {
    totalnumber.setText(String.valueOf(count));
}

public void setPinnedNotices(int count) {
    pinnednoticenumber.setText(String.valueOf(count));
}

public void setUrgentNotices(int count) {
    urgentnoticenumber.setText(String.valueOf(count));
}

// ── Button listeners ─────────────────────────────────────────────────────────
public void NewNoticeListener(java.awt.event.ActionListener listener) {
    newnotice.addActionListener(listener);   // jButton1 = "New Notice" button
}

public void DeleteNoticeListener(java.awt.event.ActionListener listener) {
    deletenotice.addActionListener(listener);
}

public void SignOutListener(java.awt.event.ActionListener listener) {
    signout.addActionListener(listener);
}

public void DashboardListener(java.awt.event.ActionListener listener) {
    dashboard.addActionListener(listener);
}

public void ProfileListener(java.awt.event.ActionListener listener) {
    profile.addActionListener(listener);
}

public void StudentsListener(java.awt.event.ActionListener listener) {
    students.addActionListener(listener); 
}
 
public void ComplaintsListener(java.awt.event.ActionListener listener) {
    complaints.addActionListener(listener);
}
 
public void RoomDetailsListener(java.awt.event.ActionListener listener) {
    roomdetails.addActionListener(listener);
}
 
public void RoomAllocationListener(java.awt.event.ActionListener listener) {
    roomallocation.addActionListener(listener);
}
 
}
