/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class RoomDetailsExpand extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomDetailsExpand.class.getName());

    /**
     * Creates new form roomDetailsExpand
     */
    public RoomDetailsExpand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        roomnumberlabel = new javax.swing.JLabel();
        roomnumbertextfield = new javax.swing.JTextField();
        blocklabel = new javax.swing.JLabel();
        blockcombobox = new javax.swing.JComboBox<>();
        floorlabel = new javax.swing.JLabel();
        floortextfield = new javax.swing.JTextField();
        typelabel = new javax.swing.JLabel();
        typecombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ficility1 = new javax.swing.JCheckBox();
        facility2 = new javax.swing.JCheckBox();
        facility3 = new javax.swing.JCheckBox();
        facility4 = new javax.swing.JCheckBox();
        cancelbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        feeslabel = new javax.swing.JLabel();
        feestextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backgroundpanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundpanel.setLayout(null);

        title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        title.setText("Add New Room");
        backgroundpanel.add(title);
        title.setBounds(10, 10, 120, 16);

        roomnumberlabel.setText("Room Number");
        backgroundpanel.add(roomnumberlabel);
        roomnumberlabel.setBounds(10, 40, 110, 16);
        backgroundpanel.add(roomnumbertextfield);
        roomnumbertextfield.setBounds(10, 60, 170, 22);

        blocklabel.setText("Block");
        backgroundpanel.add(blocklabel);
        blocklabel.setBounds(220, 40, 50, 16);

        blockcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block A", "Block B", "Block C", "Block D" }));
        backgroundpanel.add(blockcombobox);
        blockcombobox.setBounds(220, 60, 170, 22);

        floorlabel.setText("Floor");
        backgroundpanel.add(floorlabel);
        floorlabel.setBounds(10, 110, 50, 16);
        backgroundpanel.add(floortextfield);
        floortextfield.setBounds(10, 130, 170, 22);

        typelabel.setText("Type");
        backgroundpanel.add(typelabel);
        typelabel.setBounds(220, 110, 50, 16);

        typecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        backgroundpanel.add(typecombobox);
        typecombobox.setBounds(220, 130, 170, 22);

        jLabel1.setText("Facilities");
        backgroundpanel.add(jLabel1);
        jLabel1.setBounds(10, 180, 80, 16);

        ficility1.setText("Wi-Fi");
        backgroundpanel.add(ficility1);
        ficility1.setBounds(10, 200, 170, 20);

        facility2.setText("AC/Heater");
        backgroundpanel.add(facility2);
        facility2.setBounds(220, 200, 170, 20);

        facility3.setText("Power Outlet");
        backgroundpanel.add(facility3);
        facility3.setBounds(10, 230, 180, 20);

        facility4.setText("Water Supply");
        backgroundpanel.add(facility4);
        facility4.setBounds(220, 230, 170, 20);

        cancelbtn.setText("Cancel");
        backgroundpanel.add(cancelbtn);
        cancelbtn.setBounds(10, 330, 170, 30);

        addbtn.setBackground(new java.awt.Color(99, 102, 255));
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add room");
        backgroundpanel.add(addbtn);
        addbtn.setBounds(220, 330, 170, 30);

        feeslabel.setText("Fees");
        backgroundpanel.add(feeslabel);
        feeslabel.setBounds(10, 270, 37, 16);
        backgroundpanel.add(feestextfield);
        feestextfield.setBounds(10, 290, 180, 22);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 400, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoomDetailsExpand().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JComboBox<String> blockcombobox;
    private javax.swing.JLabel blocklabel;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JCheckBox facility2;
    private javax.swing.JCheckBox facility3;
    private javax.swing.JCheckBox facility4;
    private javax.swing.JLabel feeslabel;
    private javax.swing.JTextField feestextfield;
    private javax.swing.JCheckBox ficility1;
    private javax.swing.JLabel floorlabel;
    private javax.swing.JTextField floortextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel roomnumberlabel;
    private javax.swing.JTextField roomnumbertextfield;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> typecombobox;
    private javax.swing.JLabel typelabel;
    // End of variables declaration//GEN-END:variables

public String getRoomNumber()     { return roomnumbertextfield.getText().trim(); }
public String getBlock()          { return blockcombobox.getSelectedItem().toString(); }
public String getFloor()          { return floortextfield.getText().trim(); }
public String getRoomType()           { return typecombobox.getSelectedItem().toString(); }
public String getFee()              {return feestextfield.getText().trim();}
 
public java.util.List<String> getFacilities() {
    java.util.List<String> f = new java.util.ArrayList<>();
    if (ficility1.isSelected()) f.add("Wi-Fi");
    if (facility2.isSelected()) f.add("AC/Heater");
    if (facility3.isSelected()) f.add("Power Outlet");
    if (facility4.isSelected()) f.add("Water Supply");
    return f;
}
 
public void AddRoomListener(java.awt.event.ActionListener l)    { addbtn.addActionListener(l); }
public void CancelListener(java.awt.event.ActionListener l)     { cancelbtn.addActionListener(l); }
}
