/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SkyLine Computer
 */
public class RoomAllocation1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomAllocation1.class.getName());

    /**
     * Creates new form RoomAllocation
     */
    public RoomAllocation1() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        Cityscape = new javax.swing.JLabel();
        Administration = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        Students = new javax.swing.JButton();
        Complaints = new javax.swing.JButton();
        SignOut = new javax.swing.JButton();
        MealRoutine = new javax.swing.JButton();
        Notice = new javax.swing.JButton();
        RoomDetails = new javax.swing.JButton();
        RoomAllocation = new javax.swing.JButton();
        Admindashboard = new javax.swing.JLabel();
        Welcomeback = new javax.swing.JLabel();
        Notification = new javax.swing.JButton();
        roomallocation = new javax.swing.JLabel();
        assignroomdesc = new javax.swing.JLabel();
        paymentdetails = new javax.swing.JButton();
        card2 = new javax.swing.JPanel();
        totalallocation = new javax.swing.JLabel();
        allocationcount = new javax.swing.JLabel();
        card4 = new javax.swing.JPanel();
        availablerooms = new javax.swing.JLabel();
        Roomcount = new javax.swing.JLabel();
        card3 = new javax.swing.JPanel();
        Totalstudents = new javax.swing.JLabel();
        Studentcount = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rooms = new javax.swing.JPanel();
        roomallocate = new javax.swing.JLabel();
        roomspanel = new javax.swing.JPanel();
        roomnumber = new javax.swing.JLabel();
        typeblockandfloor = new javax.swing.JLabel();
        facility1 = new javax.swing.JLabel();
        facility2 = new javax.swing.JLabel();
        availablebeds = new javax.swing.JLabel();
        bedfree = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Studentspendingroom = new javax.swing.JPanel();
        pendingroom = new javax.swing.JLabel();
        studentpanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        idandprogram = new javax.swing.JLabel();
        datejoined = new javax.swing.JLabel();
        currentallocation = new javax.swing.JPanel();
        allocation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BackgroundPanel.setLayout(null);

        Cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cityscape.setForeground(new java.awt.Color(255, 255, 255));
        Cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        Cityscape.setText("Cityscape");
        BackgroundPanel.add(Cityscape);
        Cityscape.setBounds(20, 20, 170, 36);

        Administration.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Administration.setForeground(new java.awt.Color(194, 122, 255));
        Administration.setText("Administration");
        BackgroundPanel.add(Administration);
        Administration.setBounds(20, 180, 70, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        BackgroundPanel.add(dashboard);
        dashboard.setBounds(-40, 210, 260, 43);

        Students.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Students.setForeground(new java.awt.Color(255, 255, 255));
        Students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N
        Students.setText("Students");
        Students.setBorderPainted(false);
        Students.setContentAreaFilled(false);
        BackgroundPanel.add(Students);
        Students.setBounds(0, 270, 160, 43);

        Complaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Complaints.setForeground(new java.awt.Color(255, 255, 255));
        Complaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my complaints.png"))); // NOI18N
        Complaints.setText("Complaints");
        Complaints.setBorderPainted(false);
        Complaints.setContentAreaFilled(false);
        BackgroundPanel.add(Complaints);
        Complaints.setBounds(-40, 330, 260, 43);

        SignOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign out.png"))); // NOI18N
        SignOut.setText("Sign Out");
        SignOut.setBorderPainted(false);
        SignOut.setContentAreaFilled(false);
        BackgroundPanel.add(SignOut);
        SignOut.setBounds(0, 780, 170, 43);

        MealRoutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MealRoutine.setForeground(new java.awt.Color(255, 255, 255));
        MealRoutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meal routine.png"))); // NOI18N
        MealRoutine.setText("Meal Routine");
        MealRoutine.setBorderPainted(false);
        MealRoutine.setContentAreaFilled(false);
        BackgroundPanel.add(MealRoutine);
        MealRoutine.setBounds(0, 390, 190, 43);

        Notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Notice.setForeground(new java.awt.Color(255, 255, 255));
        Notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notice.png"))); // NOI18N
        Notice.setText("Notice");
        Notice.setBorderPainted(false);
        Notice.setContentAreaFilled(false);
        BackgroundPanel.add(Notice);
        Notice.setBounds(-30, 450, 200, 43);

        RoomDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoomDetails.setForeground(new java.awt.Color(255, 255, 255));
        RoomDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomdetails.png"))); // NOI18N
        RoomDetails.setText("Room Details");
        RoomDetails.setBorderPainted(false);
        RoomDetails.setContentAreaFilled(false);
        BackgroundPanel.add(RoomDetails);
        RoomDetails.setBounds(-30, 510, 260, 43);

        RoomAllocation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoomAllocation.setForeground(new java.awt.Color(255, 255, 255));
        RoomAllocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomallocation.png"))); // NOI18N
        RoomAllocation.setText("Room Allocation");
        RoomAllocation.setBorderPainted(false);
        RoomAllocation.setContentAreaFilled(false);
        BackgroundPanel.add(RoomAllocation);
        RoomAllocation.setBounds(0, 570, 220, 43);

        Admindashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Admindashboard.setText("Admin Dashboard");
        BackgroundPanel.add(Admindashboard);
        Admindashboard.setBounds(300, 0, 204, 32);

        Welcomeback.setText("Welcome Back");
        BackgroundPanel.add(Welcomeback);
        Welcomeback.setBounds(350, 30, 260, 16);

        Notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        Notification.setBorderPainted(false);
        Notification.setContentAreaFilled(false);
        BackgroundPanel.add(Notification);
        Notification.setBounds(1440, 10, 30, 40);

        roomallocation.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        roomallocation.setText("Room Allocation");
        BackgroundPanel.add(roomallocation);
        roomallocation.setBounds(300, 70, 220, 32);

        assignroomdesc.setText("Assign rooms to students and manage allocation.");
        BackgroundPanel.add(assignroomdesc);
        assignroomdesc.setBounds(300, 100, 370, 16);

        paymentdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymentdetails.setForeground(new java.awt.Color(255, 255, 255));
        paymentdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomallocation.png"))); // NOI18N
        paymentdetails.setText("Payment Details");
        paymentdetails.setBorderPainted(false);
        paymentdetails.setContentAreaFilled(false);
        paymentdetails.addActionListener(this::paymentdetailsActionPerformed);
        BackgroundPanel.add(paymentdetails);
        paymentdetails.setBounds(-20, 630, 260, 43);

        card2.setBackground(new java.awt.Color(255, 255, 255));
        card2.setLayout(null);

        totalallocation.setForeground(new java.awt.Color(153, 161, 175));
        totalallocation.setText("Total Allocation");
        card2.add(totalallocation);
        totalallocation.setBounds(20, 10, 110, 16);

        allocationcount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        allocationcount.setForeground(new java.awt.Color(102, 255, 0));
        allocationcount.setText("32");
        card2.add(allocationcount);
        allocationcount.setBounds(30, 40, 37, 20);

        BackgroundPanel.add(card2);
        card2.setBounds(1200, 160, 310, 100);

        card4.setBackground(new java.awt.Color(255, 255, 255));
        card4.setLayout(null);

        availablerooms.setForeground(new java.awt.Color(153, 161, 175));
        availablerooms.setText("Available Rooms");
        card4.add(availablerooms);
        availablerooms.setBounds(10, 10, 160, 16);

        Roomcount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Roomcount.setForeground(new java.awt.Color(99, 102, 255));
        Roomcount.setText("155");
        card4.add(Roomcount);
        Roomcount.setBounds(10, 40, 90, 27);

        BackgroundPanel.add(card4);
        card4.setBounds(750, 160, 310, 100);

        card3.setBackground(new java.awt.Color(255, 255, 255));
        card3.setLayout(null);

        Totalstudents.setForeground(new java.awt.Color(153, 161, 175));
        Totalstudents.setText("Pending Allocation");
        card3.add(Totalstudents);
        Totalstudents.setBounds(10, 10, 120, 16);

        Studentcount.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Studentcount.setForeground(new java.awt.Color(249, 115, 22));
        Studentcount.setText("155");
        card3.add(Studentcount);
        Studentcount.setBounds(10, 40, 34, 30);

        BackgroundPanel.add(card3);
        card3.setBounds(300, 160, 300, 100);

        rooms.setBackground(new java.awt.Color(255, 255, 255));
        rooms.setLayout(null);

        roomallocate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomallocate.setText("Available Rooms");
        rooms.add(roomallocate);
        roomallocate.setBounds(10, 0, 180, 30);

        roomspanel.setLayout(null);

        roomnumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roomnumber.setText("Room 101A");
        roomspanel.add(roomnumber);
        roomnumber.setBounds(50, 0, 110, 16);

        typeblockandfloor.setForeground(new java.awt.Color(153, 161, 175));
        typeblockandfloor.setText("Block A     Floor 1      Single    ");
        roomspanel.add(typeblockandfloor);
        typeblockandfloor.setBounds(50, 20, 210, 16);

        facility1.setText("wifi");
        roomspanel.add(facility1);
        facility1.setBounds(50, 40, 19, 16);

        facility2.setText("water supply");
        roomspanel.add(facility2);
        facility2.setBounds(110, 40, 100, 16);

        availablebeds.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        availablebeds.setForeground(new java.awt.Color(0, 204, 51));
        availablebeds.setText("1");
        roomspanel.add(availablebeds);
        availablebeds.setBounds(490, 0, 37, 30);

        bedfree.setText("Bed Free");
        roomspanel.add(bedfree);
        bedfree.setBounds(470, 30, 60, 16);

        rooms.add(roomspanel);
        roomspanel.setBounds(10, 50, 530, 70);

        jScrollPane3.setViewportView(rooms);

        BackgroundPanel.add(jScrollPane3);
        jScrollPane3.setBounds(930, 310, 580, 300);

        Studentspendingroom.setBackground(new java.awt.Color(255, 255, 255));
        Studentspendingroom.setLayout(null);

        pendingroom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pendingroom.setText("Students Pending Room");
        Studentspendingroom.add(pendingroom);
        pendingroom.setBounds(10, 10, 240, 25);

        studentpanel.setLayout(null);

        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setText("Hridayash Shrestha");
        studentpanel.add(name);
        name.setBounds(10, 0, 310, 16);

        idandprogram.setText("student-id     program");
        studentpanel.add(idandprogram);
        idandprogram.setBounds(10, 10, 220, 40);

        datejoined.setForeground(new java.awt.Color(153, 161, 175));
        datejoined.setText("Joined April 20,2025");
        studentpanel.add(datejoined);
        datejoined.setBounds(10, 40, 140, 16);

        Studentspendingroom.add(studentpanel);
        studentpanel.setBounds(10, 50, 530, 60);

        jScrollPane2.setViewportView(Studentspendingroom);

        BackgroundPanel.add(jScrollPane2);
        jScrollPane2.setBounds(300, 310, 580, 300);

        currentallocation.setBackground(new java.awt.Color(255, 255, 255));
        currentallocation.setLayout(null);

        allocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allocation.setText("Current Allocation");
        currentallocation.add(allocation);
        allocation.setBounds(20, 10, 140, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        currentallocation.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 1170, 110);

        BackgroundPanel.add(currentallocation);
        currentallocation.setBounds(300, 650, 1210, 180);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminbackground.png"))); // NOI18N
        Background.setText("Background");
        BackgroundPanel.add(Background);
        Background.setBounds(0, 0, 1550, 840);

        getContentPane().add(BackgroundPanel);
        BackgroundPanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentdetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoomAllocation1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admindashboard;
    private javax.swing.JLabel Administration;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel Cityscape;
    private javax.swing.JButton Complaints;
    private javax.swing.JButton MealRoutine;
    private javax.swing.JButton Notice;
    private javax.swing.JButton Notification;
    private javax.swing.JButton RoomAllocation;
    private javax.swing.JButton RoomDetails;
    private javax.swing.JLabel Roomcount;
    private javax.swing.JButton SignOut;
    private javax.swing.JLabel Studentcount;
    private javax.swing.JButton Students;
    private javax.swing.JPanel Studentspendingroom;
    private javax.swing.JLabel Totalstudents;
    private javax.swing.JLabel Welcomeback;
    private javax.swing.JLabel allocation;
    private javax.swing.JLabel allocationcount;
    private javax.swing.JLabel assignroomdesc;
    private javax.swing.JLabel availablebeds;
    private javax.swing.JLabel availablerooms;
    private javax.swing.JLabel bedfree;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel card4;
    private javax.swing.JPanel currentallocation;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel datejoined;
    private javax.swing.JLabel facility1;
    private javax.swing.JLabel facility2;
    private javax.swing.JLabel idandprogram;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel name;
    private javax.swing.JButton paymentdetails;
    private javax.swing.JLabel pendingroom;
    private javax.swing.JLabel roomallocate;
    private javax.swing.JLabel roomallocation;
    private javax.swing.JLabel roomnumber;
    private javax.swing.JPanel rooms;
    private javax.swing.JPanel roomspanel;
    private javax.swing.JPanel studentpanel;
    private javax.swing.JLabel totalallocation;
    private javax.swing.JLabel typeblockandfloor;
    // End of variables declaration//GEN-END:variables
public javax.swing.JTable getAllocationTable()    { return jTable1; }
public javax.swing.JPanel getStudentListPanel()   { return Studentspendingroom; }
public javax.swing.JPanel getRoomsPanel()         { return rooms; }
 
public void setStudentCount(int n)                { Studentcount.setText(String.valueOf(n)); }
public void setRoomCount(int n)                   { Roomcount.setText(String.valueOf(n)); }
public void setAllocationCount(int n)             { allocationcount.setText(String.valueOf(n)); }
 
public void DashboardListener(java.awt.event.ActionListener l)     { dashboard.addActionListener(l); }
public void NoticeListener(java.awt.event.ActionListener l)        { Notice.addActionListener(l); }
public void RoomDetailsListener(java.awt.event.ActionListener l)   { RoomDetails.addActionListener(l); }
public void StudentsListener(java.awt.event.ActionListener l)      { Students.addActionListener(l); }
public void ComplaintsListener(java.awt.event.ActionListener l)    { Complaints.addActionListener(l); }
public void SignOutListener(java.awt.event.ActionListener l)       { SignOut.addActionListener(l); }
public void PaymentDetailsListener(java.awt.event.ActionListener l)          { paymentdetails.addActionListener(l); }
public void MealRoutineListener(java.awt.event.ActionListener l)          { MealRoutine.addActionListener(l); }
}
