/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author Hridayash
 */
public class StudentMealRoutine extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentMealRoutine.class.getName());

    /**
     * Creates new form AddStudentDetails
     */
    public StudentMealRoutine() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        studentportal = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        mycomplaints = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        myprofile = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        navigation = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        editprofile = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        backgroundpanel.add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        backgroundpanel.add(profile);
        profile.setBounds(1480, 10, 41, 40);

        studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentportal.setText("Student Portal");
        backgroundpanel.add(studentportal);
        studentportal.setBounds(300, 0, 170, 30);

        welcomeback.setText("Welcome Back");
        backgroundpanel.add(welcomeback);
        welcomeback.setBounds(340, 30, 90, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        backgroundpanel.add(dashboard);
        dashboard.setBounds(10, 210, 160, 43);

        mycomplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mycomplaints.setForeground(new java.awt.Color(255, 255, 255));
        mycomplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/my complaints.png"))); // NOI18N
        mycomplaints.setText("My Complaints\n");
        mycomplaints.setBorderPainted(false);
        mycomplaints.setContentAreaFilled(false);
        backgroundpanel.add(mycomplaints);
        mycomplaints.setBounds(-10, 280, 230, 43);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        backgroundpanel.add(mealroutine);
        mealroutine.setBounds(10, 350, 180, 43);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        backgroundpanel.add(notice);
        notice.setBounds(0, 420, 140, 43);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        backgroundpanel.add(roomdetails);
        roomdetails.setBounds(0, 490, 200, 43);

        myprofile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myprofile.setForeground(new java.awt.Color(255, 255, 255));
        myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/myprofile.png"))); // NOI18N
        myprofile.setText("My Profile");
        myprofile.setBorderPainted(false);
        myprofile.setContentAreaFilled(false);
        backgroundpanel.add(myprofile);
        myprofile.setBounds(0, 560, 160, 43);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        backgroundpanel.add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        navigation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        navigation.setForeground(new java.awt.Color(81, 162, 255));
        navigation.setText("NAVIGATION");
        backgroundpanel.add(navigation);
        navigation.setBounds(20, 180, 70, 16);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        backgroundpanel.add(signout);
        signout.setBounds(0, 780, 170, 43);

        editprofile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editprofile.setText("Weekly Meal Routine");
        backgroundpanel.add(editprofile);
        editprofile.setBounds(310, 70, 200, 25);

        jPanel1.setBackground(new java.awt.Color(221, 214, 254));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 40, 217));
        jLabel2.setText("Dinner");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 10, 90, 16);

        jLabel7.setForeground(new java.awt.Color(109, 40, 217));
        jLabel7.setText("7:00 – 9:00 PM");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 30, 90, 16);

        backgroundpanel.add(jPanel1);
        jPanel1.setBounds(1160, 110, 340, 60);

        jPanel2.setBackground(new java.awt.Color(254, 215, 170));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(194, 65, 12));
        jLabel3.setText("Breakfast");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 10, 90, 16);

        jLabel5.setForeground(new java.awt.Color(194, 65, 12));
        jLabel5.setText("7:00 – 9:00 AM");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 30, 80, 16);

        backgroundpanel.add(jPanel2);
        jPanel2.setBounds(320, 110, 340, 60);

        jPanel3.setBackground(new java.awt.Color(191, 219, 254));
        jPanel3.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 78, 216));
        jLabel1.setText("Lunch");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 16);

        jLabel6.setForeground(new java.awt.Color(29, 78, 216));
        jLabel6.setText("12:00 – 2:00 PM");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 30, 90, 16);

        backgroundpanel.add(jPanel3);
        jPanel3.setBounds(740, 110, 340, 60);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setToolTipText("");
        jPanel5.setLayout(null);
        jPanel5.add(jPanel4);
        jPanel4.setBounds(0, 0, 1180, 140);

        jScrollPane1.setViewportView(jPanel5);

        backgroundpanel.add(jScrollPane1);
        jScrollPane1.setBounds(320, 190, 1180, 550);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentMealRoutine().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel cityscape;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel editprofile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mealroutine;
    private javax.swing.JButton mycomplaints;
    private javax.swing.JButton myprofile;
    private javax.swing.JLabel navigation;
    private javax.swing.JButton notice;
    private javax.swing.JButton notification;
    private javax.swing.JButton profile;
    private javax.swing.JButton roomdetails;
    private javax.swing.JButton signout;
    private javax.swing.JLabel studentportal;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables
}
