/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author Hridayash
 */
public class StudentProfile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentProfile.class.getName());

    /**
     * Creates new form AddStudentDetails
     */
    public StudentProfile() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        studentportal = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        mycomplaints = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        myprofile = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        navigation = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        profiletitle = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        editprofilebutton = new javax.swing.JButton();
        emergencycontact = new javax.swing.JPanel();
        emergencycont = new javax.swing.JLabel();
        contactinfopane = new javax.swing.JPanel();
        relation = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        security = new javax.swing.JPanel();
        accountsecurity = new javax.swing.JLabel();
        changepassword = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        changebutton = new javax.swing.JButton();
        academicdetails = new javax.swing.JPanel();
        academic = new javax.swing.JLabel();
        yearofstudy = new javax.swing.JLabel();
        semester = new javax.swing.JLabel();
        stidentid = new javax.swing.JLabel();
        program = new javax.swing.JLabel();
        yearofstudylabel = new javax.swing.JLabel();
        semesterlabel = new javax.swing.JLabel();
        studentidlabel = new javax.swing.JLabel();
        programlabel = new javax.swing.JLabel();
        personalinformation = new javax.swing.JPanel();
        personalinfo = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JLabel();
        nationality = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        nationalitylabel = new javax.swing.JLabel();
        fullnamelabe = new javax.swing.JLabel();
        details = new javax.swing.JPanel();
        namedetails = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        years = new javax.swing.JLabel();
        detailsbg = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        backgroundpanel.add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        backgroundpanel.add(profile);
        profile.setBounds(1480, 10, 41, 40);

        studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentportal.setText("Student Portal");
        backgroundpanel.add(studentportal);
        studentportal.setBounds(300, 0, 170, 30);

        welcomeback.setText("Welcome Back");
        backgroundpanel.add(welcomeback);
        welcomeback.setBounds(300, 30, 260, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        backgroundpanel.add(dashboard);
        dashboard.setBounds(-20, 210, 220, 43);

        mycomplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mycomplaints.setForeground(new java.awt.Color(255, 255, 255));
        mycomplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/my complaints.png"))); // NOI18N
        mycomplaints.setText("My Complaints\n");
        mycomplaints.setBorderPainted(false);
        mycomplaints.setContentAreaFilled(false);
        backgroundpanel.add(mycomplaints);
        mycomplaints.setBounds(-10, 280, 230, 43);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        backgroundpanel.add(mealroutine);
        mealroutine.setBounds(-10, 350, 220, 43);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        backgroundpanel.add(notice);
        notice.setBounds(0, 420, 140, 43);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        backgroundpanel.add(roomdetails);
        roomdetails.setBounds(0, 490, 200, 43);

        myprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myprofile.setForeground(new java.awt.Color(255, 255, 255));
        myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/myprofile.png"))); // NOI18N
        myprofile.setText("My Profile");
        myprofile.setBorderPainted(false);
        myprofile.setContentAreaFilled(false);
        backgroundpanel.add(myprofile);
        myprofile.setBounds(-20, 560, 220, 43);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        backgroundpanel.add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        navigation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        navigation.setForeground(new java.awt.Color(81, 162, 255));
        navigation.setText("NAVIGATION");
        backgroundpanel.add(navigation);
        navigation.setBounds(20, 180, 70, 16);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        backgroundpanel.add(signout);
        signout.setBounds(0, 780, 170, 43);

        profiletitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profiletitle.setText("My Profile");
        backgroundpanel.add(profiletitle);
        profiletitle.setBounds(310, 90, 110, 25);

        desc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 161, 175));
        desc.setText("Manage your personal information");
        backgroundpanel.add(desc);
        desc.setBounds(310, 110, 270, 30);

        editprofilebutton.setText("Edit Profile");
        backgroundpanel.add(editprofilebutton);
        editprofilebutton.setBounds(1415, 120, 100, 23);

        emergencycontact.setBackground(new java.awt.Color(255, 255, 255));
        emergencycontact.setLayout(null);

        emergencycont.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emergencycont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/emergencycontact.png"))); // NOI18N
        emergencycont.setText("Emergency Contact");
        emergencycontact.add(emergencycont);
        emergencycont.setBounds(10, 10, 180, 24);

        contactinfopane.setBackground(new java.awt.Color(254, 202, 202));
        contactinfopane.setLayout(null);

        relation.setText("Ram Bahadur(Brother)");
        contactinfopane.add(relation);
        relation.setBounds(10, 0, 140, 20);

        contact.setForeground(new java.awt.Color(231, 0, 11));
        contact.setText("9811111111");
        contactinfopane.add(contact);
        contact.setBounds(10, 20, 100, 16);

        emergencycontact.add(contactinfopane);
        contactinfopane.setBounds(20, 40, 510, 40);

        backgroundpanel.add(emergencycontact);
        emergencycontact.setBounds(970, 590, 550, 90);

        security.setBackground(new java.awt.Color(255, 255, 255));
        security.setLayout(null);

        accountsecurity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accountsecurity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/accountsecurity.png"))); // NOI18N
        accountsecurity.setText("Account Security");
        security.add(accountsecurity);
        accountsecurity.setBounds(10, 10, 180, 24);

        changepassword.setBackground(new java.awt.Color(248, 250, 252));
        changepassword.setLayout(null);

        Password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Password.setText("Password");
        changepassword.add(Password);
        Password.setBounds(10, 10, 100, 16);

        changebutton.setBackground(new java.awt.Color(239, 246, 255));
        changebutton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        changebutton.setForeground(new java.awt.Color(21, 93, 252));
        changebutton.setText("Change");
        changepassword.add(changebutton);
        changebutton.setBounds(240, 10, 72, 21);

        security.add(changepassword);
        changepassword.setBounds(10, 40, 330, 40);

        backgroundpanel.add(security);
        security.setBounds(308, 720, 1220, 90);

        academicdetails.setBackground(new java.awt.Color(255, 255, 255));
        academicdetails.setLayout(null);

        academic.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        academic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/academic.png"))); // NOI18N
        academic.setText("Academic Details");
        academicdetails.add(academic);
        academic.setBounds(10, 10, 180, 24);

        yearofstudy.setBackground(new java.awt.Color(153, 161, 175));
        yearofstudy.setForeground(new java.awt.Color(153, 161, 175));
        yearofstudy.setText("Year of Study");
        academicdetails.add(yearofstudy);
        yearofstudy.setBounds(10, 100, 100, 16);

        semester.setBackground(new java.awt.Color(153, 161, 175));
        semester.setForeground(new java.awt.Color(153, 161, 175));
        semester.setText("Semester");
        academicdetails.add(semester);
        semester.setBounds(10, 150, 70, 16);

        stidentid.setBackground(new java.awt.Color(153, 161, 175));
        stidentid.setForeground(new java.awt.Color(153, 161, 175));
        stidentid.setText("Student Id");
        academicdetails.add(stidentid);
        stidentid.setBounds(10, 200, 70, 16);

        program.setBackground(new java.awt.Color(153, 161, 175));
        program.setForeground(new java.awt.Color(153, 161, 175));
        program.setText("Program");
        academicdetails.add(program);
        program.setBounds(10, 50, 70, 16);

        yearofstudylabel.setText("1st Year");
        academicdetails.add(yearofstudylabel);
        yearofstudylabel.setBounds(10, 120, 270, 16);

        semesterlabel.setText("2nd");
        academicdetails.add(semesterlabel);
        semesterlabel.setBounds(10, 170, 270, 16);

        studentidlabel.setText("2");
        academicdetails.add(studentidlabel);
        studentidlabel.setBounds(10, 220, 270, 16);

        programlabel.setText("Computing");
        academicdetails.add(programlabel);
        programlabel.setBounds(10, 70, 270, 16);

        backgroundpanel.add(academicdetails);
        academicdetails.setBounds(970, 320, 550, 250);

        personalinformation.setBackground(new java.awt.Color(255, 255, 255));
        personalinformation.setLayout(null);

        personalinfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personalinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/user.png"))); // NOI18N
        personalinfo.setText("Personal Information");
        personalinformation.add(personalinfo);
        personalinfo.setBounds(10, 10, 180, 24);

        fullname.setBackground(new java.awt.Color(153, 161, 175));
        fullname.setForeground(new java.awt.Color(153, 161, 175));
        fullname.setText("Full Name");
        personalinformation.add(fullname);
        fullname.setBounds(10, 60, 70, 16);

        email.setBackground(new java.awt.Color(153, 161, 175));
        email.setForeground(new java.awt.Color(153, 161, 175));
        email.setText("Email");
        personalinformation.add(email);
        email.setBounds(10, 110, 70, 16);

        phone.setBackground(new java.awt.Color(153, 161, 175));
        phone.setForeground(new java.awt.Color(153, 161, 175));
        phone.setText("Phone");
        personalinformation.add(phone);
        phone.setBounds(10, 160, 70, 16);

        dateofbirth.setBackground(new java.awt.Color(153, 161, 175));
        dateofbirth.setForeground(new java.awt.Color(153, 161, 175));
        dateofbirth.setText("Date of Birth");
        personalinformation.add(dateofbirth);
        dateofbirth.setBounds(10, 210, 140, 16);

        nationality.setBackground(new java.awt.Color(153, 161, 175));
        nationality.setForeground(new java.awt.Color(153, 161, 175));
        nationality.setText("Nationality");
        personalinformation.add(nationality);
        nationality.setBounds(10, 260, 70, 16);

        emaillabel.setText("shresthahridayash007@gmail.com");
        personalinformation.add(emaillabel);
        emaillabel.setBounds(10, 130, 320, 16);

        phonelabel.setText("9800000000");
        personalinformation.add(phonelabel);
        phonelabel.setBounds(10, 180, 320, 16);

        doblabel.setText("2007-01-02");
        personalinformation.add(doblabel);
        doblabel.setBounds(10, 230, 320, 16);

        nationalitylabel.setText("Nepali");
        personalinformation.add(nationalitylabel);
        nationalitylabel.setBounds(10, 280, 320, 16);

        fullnamelabe.setText("hridayash");
        personalinformation.add(fullnamelabe);
        fullnamelabe.setBounds(10, 80, 320, 16);

        backgroundpanel.add(personalinformation);
        personalinformation.setBounds(310, 320, 620, 360);

        details.setBackground(new java.awt.Color(255, 255, 255));
        details.setLayout(null);

        namedetails.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namedetails.setText("Hridayash");
        details.add(namedetails);
        namedetails.setBounds(30, 50, 260, 30);

        id.setText("Student id-2");
        details.add(id);
        id.setBounds(30, 80, 90, 16);

        years.setText("1st Year, 2nd Semester");
        details.add(years);
        years.setBounds(150, 80, 180, 16);

        detailsbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/studentdetailsbackground.png"))); // NOI18N
        details.add(detailsbg);
        detailsbg.setBounds(0, 0, 1210, 110);

        backgroundpanel.add(details);
        details.setBounds(310, 160, 1210, 110);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JLabel academic;
    private javax.swing.JPanel academicdetails;
    private javax.swing.JLabel accountsecurity;
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JButton changebutton;
    private javax.swing.JPanel changepassword;
    private javax.swing.JLabel cityscape;
    private javax.swing.JLabel contact;
    private javax.swing.JPanel contactinfopane;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JLabel desc;
    private javax.swing.JPanel details;
    private javax.swing.JLabel detailsbg;
    private javax.swing.JLabel doblabel;
    private javax.swing.JButton editprofilebutton;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JLabel emergencycont;
    private javax.swing.JPanel emergencycontact;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel fullnamelabe;
    private javax.swing.JLabel id;
    private javax.swing.JButton mealroutine;
    private javax.swing.JButton mycomplaints;
    private javax.swing.JButton myprofile;
    private javax.swing.JLabel namedetails;
    private javax.swing.JLabel nationality;
    private javax.swing.JLabel nationalitylabel;
    private javax.swing.JLabel navigation;
    private javax.swing.JButton notice;
    private javax.swing.JButton notification;
    private javax.swing.JLabel personalinfo;
    private javax.swing.JPanel personalinformation;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JButton profile;
    private javax.swing.JLabel profiletitle;
    private javax.swing.JLabel program;
    private javax.swing.JLabel programlabel;
    private javax.swing.JLabel relation;
    private javax.swing.JButton roomdetails;
    private javax.swing.JPanel security;
    private javax.swing.JLabel semester;
    private javax.swing.JLabel semesterlabel;
    private javax.swing.JButton signout;
    private javax.swing.JLabel stidentid;
    private javax.swing.JLabel studentidlabel;
    private javax.swing.JLabel studentportal;
    private javax.swing.JLabel welcomeback;
    private javax.swing.JLabel yearofstudy;
    private javax.swing.JLabel yearofstudylabel;
    private javax.swing.JLabel years;
    // End of variables declaration//GEN-END:variables
public void ChangePasswordListener(java.awt.event.ActionListener listener) {
    changebutton.addActionListener(listener);
}
public void EditProfileListener(java.awt.event.ActionListener listener) {
    editprofilebutton.addActionListener(listener);
}
public void DashboardListener(java.awt.event.ActionListener listener) {
    dashboard.addActionListener(listener);
}
public void MyComplaintsListener(java.awt.event.ActionListener listener) {
    mycomplaints.addActionListener(listener);
}
public void MealRoutineListener(java.awt.event.ActionListener listener) {
    mealroutine.addActionListener(listener);
}
public void NoticeListener(java.awt.event.ActionListener listener) {
    notice.addActionListener(listener);
}
public void RoomDetailsListener(java.awt.event.ActionListener listener) {
    roomdetails.addActionListener(listener);
}
public void MyProfileListener(java.awt.event.ActionListener listener) {
    myprofile.addActionListener(listener);
}
public void SignOutListener(java.awt.event.ActionListener listener) {
    signout.addActionListener(listener);
}
public void NotificatinListener(java.awt.event.ActionListener listener) {
    notification.addActionListener(listener);
}
public void ProfileListener(java.awt.event.ActionListener listener) {
    profile.addActionListener(listener);
}
 
// ── Data setters (only the black "value" labels are updated, not the grey labels) ──
 
/** Header card: bold name */
public void setNameDetails(String name) {
    namedetails.setText(name);
}
/** Header card: "Student id-X" */
public void setIdLabel(String studentId) {
    id.setText(studentId);
}
/** Header card: "1st Year, 2nd Semester" */
public void setYearsLabel(String yearSemester) {
    years.setText(yearSemester);
}
 
// Personal Information — black value labels
public void setFullNameLabel(String name)   { fullnamelabe.setText(name); }
public void setEmailLabel(String mail)      { emaillabel.setText(mail); }
public void setPhoneLabel(String ph)        { phonelabel.setText(ph); }
public void setDobLabel(String dob)         { doblabel.setText(dob); }
public void setNationalityLabel(String nat) { nationalitylabel.setText(nat); }
 
// Academic Details — black value labels
public void setProgramLabel(String prog)    { programlabel.setText(prog); }
public void setYearOfStudyLabel(String y)   { yearofstudylabel.setText(y); }
public void setSemesterLabel(String sem)    { semesterlabel.setText(sem); }
public void setStudentIdLabel(String sid)   { studentidlabel.setText(sid); }
 
// Emergency Contact — black value labels
public void setEmergencyContactLabel(String nameAndRelation) { relation.setText(nameAndRelation); }
public void setEmergencyNumberLabel(String number)           { contact.setText(number); }
 
public void setWelcomeUser(String username) {
    welcomeback.setText("Welcome back, " + username + "!");
}
}
