/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author Hridayash
 */
public class StudentMealRoutine extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentMealRoutine.class.getName());

    /**
     * Creates new form AddStudentDetails
     */
    public StudentMealRoutine() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        studentportal = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        mycomplaints = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        myprofile = new javax.swing.JButton();
        paymenthistory = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        makepayment = new javax.swing.JButton();
        navigation = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        editprofile = new javax.swing.JLabel();
        dinnerpanel = new javax.swing.JPanel();
        dinnerlabel = new javax.swing.JLabel();
        dinnertime = new javax.swing.JLabel();
        dinnericon = new javax.swing.JLabel();
        beakfastpanel = new javax.swing.JPanel();
        breakfastlabel = new javax.swing.JLabel();
        breakfasttime = new javax.swing.JLabel();
        breakfasticon = new javax.swing.JLabel();
        lunchpanel = new javax.swing.JPanel();
        lunchlabel = new javax.swing.JLabel();
        lunchtime = new javax.swing.JLabel();
        lunchicon = new javax.swing.JLabel();
        mealsscrollpanel = new javax.swing.JScrollPane();
        Meal = new javax.swing.JPanel();
        Sunday = new javax.swing.JPanel();
        daytitlepanel = new javax.swing.JPanel();
        daytitlelabel = new javax.swing.JLabel();
        breakfast = new javax.swing.JLabel();
        lunch = new javax.swing.JLabel();
        dinner = new javax.swing.JLabel();
        breakfast4 = new javax.swing.JLabel();
        breakfast3 = new javax.swing.JLabel();
        lunch1 = new javax.swing.JLabel();
        breakfast2 = new javax.swing.JLabel();
        bullet1 = new javax.swing.JLabel();
        bullet3 = new javax.swing.JLabel();
        bullet4 = new javax.swing.JLabel();
        bullet6 = new javax.swing.JLabel();
        lunch2 = new javax.swing.JLabel();
        lunch3 = new javax.swing.JLabel();
        dinner1 = new javax.swing.JLabel();
        dinner2 = new javax.swing.JLabel();
        dinner3 = new javax.swing.JLabel();
        breakfast1 = new javax.swing.JLabel();
        bullet2 = new javax.swing.JLabel();
        bullet7 = new javax.swing.JLabel();
        bullet9 = new javax.swing.JLabel();
        bullet5 = new javax.swing.JLabel();
        bullet10 = new javax.swing.JLabel();
        bullet8 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        backgroundpanel.add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        backgroundpanel.add(profile);
        profile.setBounds(1480, 10, 40, 40);

        studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentportal.setText("Student Portal");
        backgroundpanel.add(studentportal);
        studentportal.setBounds(300, 0, 170, 30);

        welcomeback.setText("Welcome Back");
        backgroundpanel.add(welcomeback);
        welcomeback.setBounds(340, 30, 90, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        backgroundpanel.add(dashboard);
        dashboard.setBounds(-30, 210, 240, 43);

        mycomplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mycomplaints.setForeground(new java.awt.Color(255, 255, 255));
        mycomplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my complaints.png"))); // NOI18N
        mycomplaints.setText("My Complaints\n");
        mycomplaints.setBorderPainted(false);
        mycomplaints.setContentAreaFilled(false);
        mycomplaints.addActionListener(this::mycomplaintsActionPerformed);
        backgroundpanel.add(mycomplaints);
        mycomplaints.setBounds(-30, 280, 280, 40);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        backgroundpanel.add(mealroutine);
        mealroutine.setBounds(-30, 350, 260, 43);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        backgroundpanel.add(notice);
        notice.setBounds(0, 430, 150, 32);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        backgroundpanel.add(roomdetails);
        roomdetails.setBounds(0, 500, 200, 32);

        myprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        myprofile.setForeground(new java.awt.Color(255, 255, 255));
        myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/myprofile.png"))); // NOI18N
        myprofile.setText("My Profile");
        myprofile.setBorderPainted(false);
        myprofile.setContentAreaFilled(false);
        backgroundpanel.add(myprofile);
        myprofile.setBounds(-20, 690, 220, 40);

        paymenthistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymenthistory.setForeground(new java.awt.Color(255, 255, 255));
        paymenthistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paymenthistory.png"))); // NOI18N
        paymenthistory.setText("Payment History");
        paymenthistory.setBorderPainted(false);
        paymenthistory.setContentAreaFilled(false);
        backgroundpanel.add(paymenthistory);
        paymenthistory.setBounds(-20, 620, 270, 43);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        backgroundpanel.add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        makepayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makepayment.setForeground(new java.awt.Color(255, 255, 255));
        makepayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/makepayment.png"))); // NOI18N
        makepayment.setText("Make Payment");
        makepayment.setBorderPainted(false);
        makepayment.setContentAreaFilled(false);
        backgroundpanel.add(makepayment);
        makepayment.setBounds(-20, 560, 250, 43);

        navigation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        navigation.setForeground(new java.awt.Color(81, 162, 255));
        navigation.setText("NAVIGATION");
        backgroundpanel.add(navigation);
        navigation.setBounds(20, 180, 70, 16);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        backgroundpanel.add(signout);
        signout.setBounds(0, 780, 170, 43);

        editprofile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editprofile.setText("Weekly Meal Routine");
        backgroundpanel.add(editprofile);
        editprofile.setBounds(310, 70, 200, 25);

        dinnerpanel.setBackground(new java.awt.Color(221, 214, 254));
        dinnerpanel.setLayout(null);

        dinnerlabel.setBackground(new java.awt.Color(255, 255, 255));
        dinnerlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dinnerlabel.setForeground(new java.awt.Color(109, 40, 217));
        dinnerlabel.setText("Dinner");
        dinnerpanel.add(dinnerlabel);
        dinnerlabel.setBounds(40, 10, 90, 16);

        dinnertime.setForeground(new java.awt.Color(109, 40, 217));
        dinnertime.setText("7:00 – 9:00 PM");
        dinnerpanel.add(dinnertime);
        dinnertime.setBounds(40, 30, 90, 16);

        dinnericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner.png"))); // NOI18N
        dinnerpanel.add(dinnericon);
        dinnericon.setBounds(10, 10, 37, 40);

        backgroundpanel.add(dinnerpanel);
        dinnerpanel.setBounds(1160, 110, 340, 60);

        beakfastpanel.setBackground(new java.awt.Color(254, 215, 170));
        beakfastpanel.setLayout(null);

        breakfastlabel.setBackground(new java.awt.Color(255, 255, 255));
        breakfastlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        breakfastlabel.setForeground(new java.awt.Color(194, 65, 12));
        breakfastlabel.setText("Breakfast");
        beakfastpanel.add(breakfastlabel);
        breakfastlabel.setBounds(50, 10, 90, 16);

        breakfasttime.setForeground(new java.awt.Color(194, 65, 12));
        breakfasttime.setText("7:00 – 9:00 AM");
        beakfastpanel.add(breakfasttime);
        breakfasttime.setBounds(50, 30, 80, 16);

        breakfasticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/breakfast.png"))); // NOI18N
        beakfastpanel.add(breakfasticon);
        breakfasticon.setBounds(10, 10, 30, 40);

        backgroundpanel.add(beakfastpanel);
        beakfastpanel.setBounds(320, 110, 340, 60);

        lunchpanel.setBackground(new java.awt.Color(191, 219, 254));
        lunchpanel.setLayout(null);

        lunchlabel.setBackground(new java.awt.Color(255, 255, 255));
        lunchlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lunchlabel.setForeground(new java.awt.Color(29, 78, 216));
        lunchlabel.setText("Lunch");
        lunchpanel.add(lunchlabel);
        lunchlabel.setBounds(40, 10, 90, 16);

        lunchtime.setForeground(new java.awt.Color(29, 78, 216));
        lunchtime.setText("12:00 – 2:00 PM");
        lunchpanel.add(lunchtime);
        lunchtime.setBounds(40, 30, 90, 16);

        lunchicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lunch.png"))); // NOI18N
        lunchpanel.add(lunchicon);
        lunchicon.setBounds(10, 10, 24, 40);

        backgroundpanel.add(lunchpanel);
        lunchpanel.setBounds(740, 110, 340, 60);

        Meal.setBackground(new java.awt.Color(204, 204, 204));
        Meal.setToolTipText("");
        Meal.setLayout(null);

        Sunday.setLayout(null);

        daytitlepanel.setBackground(new java.awt.Color(148, 163, 184));
        daytitlepanel.setLayout(null);

        daytitlelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        daytitlelabel.setText("Wednesday");
        daytitlepanel.add(daytitlelabel);
        daytitlelabel.setBounds(40, 0, 100, 30);

        Sunday.add(daytitlepanel);
        daytitlepanel.setBounds(0, 0, 1180, 30);

        breakfast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        breakfast.setForeground(new java.awt.Color(249, 115, 22));
        breakfast.setText("Breakfast");
        Sunday.add(breakfast);
        breakfast.setBounds(30, 40, 60, 16);

        lunch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lunch.setForeground(new java.awt.Color(59, 130, 246));
        lunch.setText("Lunch");
        Sunday.add(lunch);
        lunch.setBounds(450, 40, 37, 16);

        dinner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dinner.setForeground(new java.awt.Color(139, 92, 246));
        dinner.setText("Dinner");
        Sunday.add(dinner);
        dinner.setBounds(860, 40, 43, 16);

        breakfast4.setText("Tea/Coffee");
        Sunday.add(breakfast4);
        breakfast4.setBounds(40, 120, 80, 16);

        breakfast3.setText("Orange Juice");
        Sunday.add(breakfast3);
        breakfast3.setBounds(40, 100, 80, 16);

        lunch1.setText("Steamed Rice");
        Sunday.add(lunch1);
        lunch1.setBounds(450, 60, 80, 16);

        breakfast2.setText("Scrambled Eggs");
        Sunday.add(breakfast2);
        breakfast2.setBounds(40, 80, 110, 16);

        bullet1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet1.setForeground(new java.awt.Color(249, 115, 22));
        bullet1.setText("-");
        Sunday.add(bullet1);
        bullet1.setBounds(30, 80, 10, 16);

        bullet3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet3.setForeground(new java.awt.Color(249, 115, 22));
        bullet3.setText("-");
        Sunday.add(bullet3);
        bullet3.setBounds(30, 100, 10, 16);

        bullet4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet4.setForeground(new java.awt.Color(249, 115, 22));
        bullet4.setText("-");
        Sunday.add(bullet4);
        bullet4.setBounds(30, 120, 10, 16);

        bullet6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet6.setForeground(new java.awt.Color(59, 130, 246));
        bullet6.setText("-");
        Sunday.add(bullet6);
        bullet6.setBounds(440, 80, 10, 16);

        lunch2.setText("Rajma Curry");
        Sunday.add(lunch2);
        lunch2.setBounds(450, 80, 80, 16);

        lunch3.setText("Chicken Curry");
        Sunday.add(lunch3);
        lunch3.setBounds(450, 100, 80, 16);

        dinner1.setText("Chapati");
        Sunday.add(dinner1);
        dinner1.setBounds(870, 60, 80, 16);

        dinner2.setText("Paneer Butter Masala");
        Sunday.add(dinner2);
        dinner2.setBounds(870, 80, 120, 16);

        dinner3.setText("Veg Soup");
        Sunday.add(dinner3);
        dinner3.setBounds(870, 100, 80, 16);

        breakfast1.setText("Pancakes");
        Sunday.add(breakfast1);
        breakfast1.setBounds(40, 60, 80, 16);

        bullet2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet2.setForeground(new java.awt.Color(249, 115, 22));
        bullet2.setText("-");
        Sunday.add(bullet2);
        bullet2.setBounds(30, 60, 10, 16);

        bullet7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet7.setForeground(new java.awt.Color(59, 130, 246));
        bullet7.setText("-");
        Sunday.add(bullet7);
        bullet7.setBounds(440, 100, 10, 16);

        bullet9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet9.setForeground(new java.awt.Color(139, 92, 246));
        bullet9.setText("-");
        Sunday.add(bullet9);
        bullet9.setBounds(860, 80, 10, 16);

        bullet5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet5.setForeground(new java.awt.Color(59, 130, 246));
        bullet5.setText("-");
        Sunday.add(bullet5);
        bullet5.setBounds(440, 60, 10, 16);

        bullet10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet10.setForeground(new java.awt.Color(139, 92, 246));
        bullet10.setText("-");
        Sunday.add(bullet10);
        bullet10.setBounds(860, 100, 10, 16);

        bullet8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bullet8.setForeground(new java.awt.Color(139, 92, 246));
        bullet8.setText("-");
        Sunday.add(bullet8);
        bullet8.setBounds(860, 60, 10, 16);

        Meal.add(Sunday);
        Sunday.setBounds(0, 0, 1180, 190);

        mealsscrollpanel.setViewportView(Meal);

        backgroundpanel.add(mealsscrollpanel);
        mealsscrollpanel.setBounds(320, 190, 1180, 630);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void mycomplaintsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mycomplaintsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mycomplaintsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentMealRoutine().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Meal;
    private javax.swing.JPanel Sunday;
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JPanel beakfastpanel;
    private javax.swing.JLabel breakfast;
    private javax.swing.JLabel breakfast1;
    private javax.swing.JLabel breakfast2;
    private javax.swing.JLabel breakfast3;
    private javax.swing.JLabel breakfast4;
    private javax.swing.JLabel breakfasticon;
    private javax.swing.JLabel breakfastlabel;
    private javax.swing.JLabel breakfasttime;
    private javax.swing.JLabel bullet1;
    private javax.swing.JLabel bullet10;
    private javax.swing.JLabel bullet2;
    private javax.swing.JLabel bullet3;
    private javax.swing.JLabel bullet4;
    private javax.swing.JLabel bullet5;
    private javax.swing.JLabel bullet6;
    private javax.swing.JLabel bullet7;
    private javax.swing.JLabel bullet8;
    private javax.swing.JLabel bullet9;
    private javax.swing.JLabel cityscape;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel daytitlelabel;
    private javax.swing.JPanel daytitlepanel;
    private javax.swing.JLabel dinner;
    private javax.swing.JLabel dinner1;
    private javax.swing.JLabel dinner2;
    private javax.swing.JLabel dinner3;
    private javax.swing.JLabel dinnericon;
    private javax.swing.JLabel dinnerlabel;
    private javax.swing.JPanel dinnerpanel;
    private javax.swing.JLabel dinnertime;
    private javax.swing.JLabel editprofile;
    private javax.swing.JLabel lunch;
    private javax.swing.JLabel lunch1;
    private javax.swing.JLabel lunch2;
    private javax.swing.JLabel lunch3;
    private javax.swing.JLabel lunchicon;
    private javax.swing.JLabel lunchlabel;
    private javax.swing.JPanel lunchpanel;
    private javax.swing.JLabel lunchtime;
    private javax.swing.JButton makepayment;
    private javax.swing.JButton mealroutine;
    private javax.swing.JScrollPane mealsscrollpanel;
    private javax.swing.JButton mycomplaints;
    private javax.swing.JButton myprofile;
    private javax.swing.JLabel navigation;
    private javax.swing.JButton notice;
    private javax.swing.JButton notification;
    private javax.swing.JButton paymenthistory;
    private javax.swing.JButton profile;
    private javax.swing.JButton roomdetails;
    private javax.swing.JButton signout;
    private javax.swing.JLabel studentportal;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables
public javax.swing.JPanel getMealContainer() { return Meal; }

public void DashboardListener(java.awt.event.ActionListener l)      { dashboard.addActionListener(l); }
public void ComplaintsListener(java.awt.event.ActionListener l)     { mycomplaints.addActionListener(l); }
public void MealRoutineListener(java.awt.event.ActionListener l)    { mealroutine.addActionListener(l); }
public void NoticeListener(java.awt.event.ActionListener l)         { notice.addActionListener(l); }
public void RoomDetailsListener(java.awt.event.ActionListener l)    { roomdetails.addActionListener(l); }
public void PaymentHistoryListener(java.awt.event.ActionListener l) { paymenthistory.addActionListener(l); }
public void MyProfileListener(java.awt.event.ActionListener l)      { myprofile.addActionListener(l); }
public void SignOutListener(java.awt.event.ActionListener l)        { signout.addActionListener(l); }
public void MakePaymentListener(java.awt.event.ActionListener l)    { makepayment.addActionListener(l); }
public void MyComplaintsListener(java.awt.event.ActionListener listener) {
    mycomplaints.addActionListener(listener);
}
public void ProfileListener(java.awt.event.ActionListener listener) {
    profile.addActionListener(listener);
}
public void NotificatinListener(java.awt.event.ActionListener listener) {
    notification.addActionListener(listener);
}
}
