/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sulav
 */
public class UserRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserRegistration.class.getName());

    /**
     * Creates new form UserRegistration
     */
    public UserRegistration() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignUp = new javax.swing.JPanel();
        Password_data = new javax.swing.JPasswordField();
        Confirm_password_data = new javax.swing.JPasswordField();
        Account_exist = new javax.swing.JLabel();
        Signup = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usernamedata = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        confirm = new javax.swing.JLabel();
        SignUP = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        Email = new javax.swing.JLabel();
        Email_data = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        SignUp.setBackground(new java.awt.Color(255, 255, 255));

        Password_data.setBackground(new java.awt.Color(171, 186, 255));
        Password_data.setText("********");
        Password_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Password_dataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Password_dataFocusLost(evt);
            }
        });
        Password_data.addActionListener(this::Password_dataActionPerformed);

        Confirm_password_data.setBackground(new java.awt.Color(171, 186, 255));
        Confirm_password_data.setText("********");
        Confirm_password_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Confirm_password_dataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Confirm_password_dataFocusLost(evt);
            }
        });
        Confirm_password_data.addActionListener(this::Confirm_password_dataActionPerformed);

        Account_exist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Account_exist.setText("Already have an account?");

        Signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Signup.setText("Sign Up");

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username.setText("Username ");

        usernamedata.setBackground(new java.awt.Color(171, 186, 255));
        usernamedata.addActionListener(this::usernamedataActionPerformed);

        password.setBackground(new java.awt.Color(0, 0, 0));
        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password.setText("Password");

        confirm.setBackground(new java.awt.Color(0, 0, 0));
        confirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirm.setText("Confirm Password ");

        SignUP.setBackground(new java.awt.Color(5, 13, 153));
        SignUP.setForeground(new java.awt.Color(255, 255, 255));
        SignUP.setText("Sign up");
        SignUP.addActionListener(this::SignUPActionPerformed);

        LogIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogIn.setForeground(new java.awt.Color(5, 13, 153));
        LogIn.setText("Log in");
        LogIn.setBorderPainted(false);
        LogIn.setContentAreaFilled(false);
        LogIn.addActionListener(this::LogInActionPerformed);

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setText("Email");

        Email_data.setBackground(new java.awt.Color(171, 186, 255));
        Email_data.addActionListener(this::Email_dataActionPerformed);

        javax.swing.GroupLayout SignUpLayout = new javax.swing.GroupLayout(SignUp);
        SignUp.setLayout(SignUpLayout);
        SignUpLayout.setHorizontalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email_data, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUP, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_data, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm)
                    .addComponent(usernamedata, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirm_password_data, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SignUpLayout.createSequentialGroup()
                        .addComponent(Account_exist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogIn)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        SignUpLayout.setVerticalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Signup)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamedata, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email_data, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirm_password_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SignUP)
                .addGap(18, 18, 18)
                .addGroup(SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account_exist)
                    .addComponent(LogIn))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPanel1.add(SignUp);
        SignUp.setBounds(760, 180, 590, 540);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/WhatsApp Image 2026-05-20 at 5.01.07 PM.jpeg"))); // NOI18N
        Background.setText("jLabel1");
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1550, 840);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
LogIn LI = new LogIn();
LI.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_LogInActionPerformed

    private void SignUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUPActionPerformed

    private void usernamedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamedataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamedataActionPerformed

    private void Confirm_password_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_password_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_password_dataActionPerformed

    private void Password_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_dataActionPerformed

    private void Email_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_dataActionPerformed

    private void Password_dataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_dataFocusGained
        // TODO add your handling code here:
        if(Password_data.getText().equals("********")){
            Password_data.setText("");
        }
    }//GEN-LAST:event_Password_dataFocusGained

    private void Password_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Password_dataFocusLost
        // TODO add your handling code here:
        if(Password_data.getText().equals("")){
            Password_data.setText("********");
        }
    }//GEN-LAST:event_Password_dataFocusLost

    private void Confirm_password_dataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Confirm_password_dataFocusGained
         if(Confirm_password_data.getText().equals("********")){
            Confirm_password_data.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_password_dataFocusGained
    }
    private void Confirm_password_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Confirm_password_dataFocusLost
        if(Confirm_password_data.getText().equals("")){
            Confirm_password_data.setText("*********");// TODO add your handling code here:
    }//GEN-LAST:event_Confirm_password_dataFocusLost
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserRegistration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account_exist;
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField Confirm_password_data;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Email_data;
    private javax.swing.JButton LogIn;
    private javax.swing.JPasswordField Password_data;
    private javax.swing.JButton SignUP;
    private javax.swing.JPanel SignUp;
    private javax.swing.JLabel Signup;
    private javax.swing.JLabel confirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernamedata;
    // End of variables declaration//GEN-END:variables
}
