/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class VerifyOtp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerifyOtp.class.getName());

    /**
     * Creates new form VerifyOtp
     */
    public VerifyOtp() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        verifyotppanel = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        verifyotpheader = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        code1 = new javax.swing.JTextField();
        code2 = new javax.swing.JTextField();
        code3 = new javax.swing.JTextField();
        code4 = new javax.swing.JTextField();
        code5 = new javax.swing.JTextField();
        code6 = new javax.swing.JTextField();
        verify = new javax.swing.JButton();
        didntreceive = new javax.swing.JLabel();
        resend = new javax.swing.JButton();
        verifyotpicon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        verifyotppanel.setBackground(new java.awt.Color(255, 255, 255));
        verifyotppanel.setLayout(null);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/arrow.png"))); // NOI18N
        back.setText("Back");
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(this::backActionPerformed);
        verifyotppanel.add(back);
        back.setBounds(0, 10, 90, 31);

        verifyotpheader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        verifyotpheader.setText("Verify OTP");
        verifyotppanel.add(verifyotpheader);
        verifyotpheader.setBounds(200, 60, 100, 25);

        desc.setForeground(new java.awt.Color(153, 161, 175));
        desc.setText("We have sent a 6-digit code to");
        verifyotppanel.add(desc);
        desc.setBounds(170, 90, 170, 16);

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        verifyotppanel.add(email);
        email.setBounds(197, 110, 100, 0);
        verifyotppanel.add(code1);
        code1.setBounds(50, 190, 50, 50);
        verifyotppanel.add(code2);
        code2.setBounds(120, 190, 50, 50);
        verifyotppanel.add(code3);
        code3.setBounds(190, 190, 50, 50);
        verifyotppanel.add(code4);
        code4.setBounds(260, 190, 50, 50);
        verifyotppanel.add(code5);
        code5.setBounds(330, 190, 50, 50);
        verifyotppanel.add(code6);
        code6.setBounds(400, 190, 50, 50);

        verify.setBackground(new java.awt.Color(47, 91, 255));
        verify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 255, 255));
        verify.setText("Verify and Continue");
        verify.addActionListener(this::verifyActionPerformed);
        verifyotppanel.add(verify);
        verify.setBounds(50, 353, 400, 50);

        didntreceive.setForeground(new java.awt.Color(153, 161, 175));
        didntreceive.setText("Didn't receive the code?");
        verifyotppanel.add(didntreceive);
        didntreceive.setBounds(160, 330, 130, 16);

        resend.setForeground(new java.awt.Color(47, 91, 255));
        resend.setText("Resend OTP");
        resend.setBorderPainted(false);
        resend.setContentAreaFilled(false);
        resend.addActionListener(this::resendActionPerformed);
        verifyotppanel.add(resend);
        resend.setBounds(270, 323, 100, 30);

        verifyotpicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/verifyotp.png"))); // NOI18N
        verifyotppanel.add(verifyotpicon);
        verifyotpicon.setBounds(210, 0, 64, 64);

        backgroundpanel.add(verifyotppanel);
        verifyotppanel.setBounds(790, 160, 500, 480);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/forgetpasswordbg.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resendActionPerformed
       
    
// TODO add your handling code here:
    }//GEN-LAST:event_resendActionPerformed

    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed




    
    }//GEN-LAST:event_verifyActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VerifyOtp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JTextField code1;
    private javax.swing.JTextField code2;
    private javax.swing.JTextField code3;
    private javax.swing.JTextField code4;
    private javax.swing.JTextField code5;
    private javax.swing.JTextField code6;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel didntreceive;
    private javax.swing.JLabel email;
    private javax.swing.JButton resend;
    private javax.swing.JButton verify;
    private javax.swing.JLabel verifyotpheader;
    private javax.swing.JLabel verifyotpicon;
    private javax.swing.JPanel verifyotppanel;
    // End of variables declaration//GEN-END:variables
}
