/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class ViewComplaintExpand extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewComplaintExpand.class.getName());

    /**
     * Creates new form IssueNotice
     */
    public ViewComplaintExpand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewcomplaint = new javax.swing.JPanel();
        complaintdetail = new javax.swing.JLabel();
        priority = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        categorypanel = new javax.swing.JPanel();
        category = new javax.swing.JLabel();
        categoryvariable = new javax.swing.JLabel();
        fileddatepanel = new javax.swing.JPanel();
        fileddate = new javax.swing.JLabel();
        datevariable = new javax.swing.JLabel();
        descpanel = new javax.swing.JPanel();
        desc = new javax.swing.JLabel();
        descscrollpanel = new javax.swing.JScrollPane();
        desctextarea = new javax.swing.JTextArea();
        studentpanel = new javax.swing.JPanel();
        student = new javax.swing.JLabel();
        studentnamevariable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        viewcomplaint.setBackground(new java.awt.Color(255, 255, 255));
        viewcomplaint.setLayout(null);

        complaintdetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        complaintdetail.setText("Complaint Details");
        viewcomplaint.add(complaintdetail);
        complaintdetail.setBounds(10, 10, 150, 16);

        priority.setText("High");
        viewcomplaint.add(priority);
        priority.setBounds(10, 40, 120, 16);

        closebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closebutton.setText("Close");
        viewcomplaint.add(closebutton);
        closebutton.setBounds(10, 290, 330, 30);

        title.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        title.setText("Title");
        viewcomplaint.add(title);
        title.setBounds(10, 60, 320, 16);

        categorypanel.setBackground(new java.awt.Color(248, 250, 252));
        categorypanel.setLayout(null);

        category.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        category.setForeground(new java.awt.Color(153, 161, 175));
        category.setText("Category");
        categorypanel.add(category);
        category.setBounds(0, 0, 60, 14);

        categoryvariable.setText("maintenance");
        categorypanel.add(categoryvariable);
        categoryvariable.setBounds(0, 10, 120, 30);

        viewcomplaint.add(categorypanel);
        categorypanel.setBounds(180, 90, 150, 40);

        fileddatepanel.setBackground(new java.awt.Color(248, 250, 252));
        fileddatepanel.setLayout(null);

        fileddate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        fileddate.setForeground(new java.awt.Color(153, 161, 175));
        fileddate.setText("Filed on");
        fileddatepanel.add(fileddate);
        fileddate.setBounds(0, 0, 60, 14);

        datevariable.setText("2025-09-08");
        fileddatepanel.add(datevariable);
        datevariable.setBounds(0, 10, 120, 30);

        viewcomplaint.add(fileddatepanel);
        fileddatepanel.setBounds(10, 150, 150, 40);

        descpanel.setBackground(new java.awt.Color(248, 250, 252));
        descpanel.setLayout(null);

        desc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 161, 175));
        desc.setText("Description");
        descpanel.add(desc);
        desc.setBounds(0, 0, 60, 14);

        desctextarea.setEditable(false);
        desctextarea.setColumns(20);
        desctextarea.setLineWrap(true);
        desctextarea.setRows(5);
        desctextarea.setWrapStyleWord(true);
        desctextarea.setFocusable(false);
        descscrollpanel.setViewportView(desctextarea);

        descpanel.add(descscrollpanel);
        descscrollpanel.setBounds(0, 20, 320, 50);

        viewcomplaint.add(descpanel);
        descpanel.setBounds(10, 200, 320, 70);

        studentpanel.setBackground(new java.awt.Color(248, 250, 252));
        studentpanel.setLayout(null);

        student.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        student.setForeground(new java.awt.Color(153, 161, 175));
        student.setText("Student");
        studentpanel.add(student);
        student.setBounds(0, 0, 60, 14);

        studentnamevariable.setText("hari");
        studentpanel.add(studentnamevariable);
        studentnamevariable.setBounds(0, 10, 120, 30);

        viewcomplaint.add(studentpanel);
        studentpanel.setBounds(10, 90, 150, 40);

        getContentPane().add(viewcomplaint);
        viewcomplaint.setBounds(0, 0, 350, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewComplaintExpand().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel category;
    private javax.swing.JPanel categorypanel;
    private javax.swing.JLabel categoryvariable;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel complaintdetail;
    private javax.swing.JLabel datevariable;
    private javax.swing.JLabel desc;
    private javax.swing.JPanel descpanel;
    private javax.swing.JScrollPane descscrollpanel;
    private javax.swing.JTextArea desctextarea;
    private javax.swing.JLabel fileddate;
    private javax.swing.JPanel fileddatepanel;
    private javax.swing.JLabel priority;
    private javax.swing.JLabel student;
    private javax.swing.JLabel studentnamevariable;
    private javax.swing.JPanel studentpanel;
    private javax.swing.JLabel title;
    private javax.swing.JPanel viewcomplaint;
    // End of variables declaration//GEN-END:variables

public void setComplaintData(model.ComplaintData c) {
    priority.setText(c.getPriority());
    title.setText(c.getTitle());
    studentnamevariable.setText(c.getUsername() != null && !c.getUsername().isEmpty()
            ? c.getUsername() : "—");
    categoryvariable.setText(c.getCategory());
    datevariable.setText(c.getFormattedDate());
    desctextarea.setText(c.getDescription());
    desctextarea.setCaretPosition(0);
}
 
public void CloseListener(java.awt.event.ActionListener listener) {
    closebutton.addActionListener(listener);
}
}
