/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pralo
 */
public class ViewPaymentDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewPaymentDetails.class.getName());

    /**
     * Creates new form PayemntD
     */
    public ViewPaymentDetails() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        Navigation = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        MyComplaints = new javax.swing.JButton();
        MealRoutine = new javax.swing.JButton();
        Notice = new javax.swing.JButton();
        RoomDetails = new javax.swing.JButton();
        Myprofile = new javax.swing.JButton();
        Dashboard1 = new javax.swing.JButton();
        makepayment = new javax.swing.JButton();
        Studentportal = new javax.swing.JLabel();
        Welcomeback = new javax.swing.JLabel();
        Notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        paymenthistory = new javax.swing.JButton();
        paymenthistorypanel = new javax.swing.JPanel();
        transactionhistorylabel = new javax.swing.JLabel();
        paymenthistorytablescrollpanel = new javax.swing.JScrollPane();
        paymenthistorytable = new javax.swing.JTable();
        descriptionpanel = new javax.swing.JPanel();
        paymentdetailslabel = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        logo.setText("Cityscape");
        getContentPane().add(logo);
        logo.setBounds(20, 10, 150, 36);

        Navigation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Navigation.setForeground(new java.awt.Color(81, 130, 255));
        Navigation.setText("NAVIGATION");
        getContentPane().add(Navigation);
        Navigation.setBounds(20, 180, 70, 16);

        Dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        Dashboard.setText("Dashbaord");
        Dashboard.setBorderPainted(false);
        Dashboard.setContentAreaFilled(false);
        getContentPane().add(Dashboard);
        Dashboard.setBounds(-20, 220, 220, 43);

        MyComplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MyComplaints.setForeground(new java.awt.Color(255, 255, 255));
        MyComplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my complaints.png"))); // NOI18N
        MyComplaints.setText("My Complaints");
        MyComplaints.setBorderPainted(false);
        MyComplaints.setContentAreaFilled(false);
        getContentPane().add(MyComplaints);
        MyComplaints.setBounds(-30, 280, 270, 43);

        MealRoutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MealRoutine.setForeground(new java.awt.Color(255, 255, 255));
        MealRoutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meal routine.png"))); // NOI18N
        MealRoutine.setText("Meal Routine");
        MealRoutine.setBorderPainted(false);
        MealRoutine.setContentAreaFilled(false);
        getContentPane().add(MealRoutine);
        MealRoutine.setBounds(-40, 340, 280, 43);

        Notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Notice.setForeground(new java.awt.Color(255, 255, 255));
        Notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notice.png"))); // NOI18N
        Notice.setText("Notice");
        Notice.setBorderPainted(false);
        Notice.setContentAreaFilled(false);
        getContentPane().add(Notice);
        Notice.setBounds(-30, 410, 210, 43);

        RoomDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RoomDetails.setForeground(new java.awt.Color(255, 255, 255));
        RoomDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomdetails.png"))); // NOI18N
        RoomDetails.setText("Room Details");
        RoomDetails.setBorderPainted(false);
        RoomDetails.setContentAreaFilled(false);
        getContentPane().add(RoomDetails);
        RoomDetails.setBounds(-20, 470, 240, 43);

        Myprofile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Myprofile.setForeground(new java.awt.Color(255, 255, 255));
        Myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/myprofile.png"))); // NOI18N
        Myprofile.setText("My Profile");
        Myprofile.setBorderPainted(false);
        Myprofile.setContentAreaFilled(false);
        getContentPane().add(Myprofile);
        Myprofile.setBounds(-20, 660, 220, 43);

        Dashboard1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Dashboard1.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign out.png"))); // NOI18N
        Dashboard1.setText("Sign out");
        Dashboard1.setBorderPainted(false);
        Dashboard1.setContentAreaFilled(false);
        getContentPane().add(Dashboard1);
        Dashboard1.setBounds(0, 780, 170, 43);

        makepayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        makepayment.setForeground(new java.awt.Color(255, 255, 255));
        makepayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/makepayment.png"))); // NOI18N
        makepayment.setText("Make Payment");
        makepayment.setBorderPainted(false);
        makepayment.setContentAreaFilled(false);
        getContentPane().add(makepayment);
        makepayment.setBounds(-20, 540, 260, 43);

        Studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Studentportal.setText("Student Portal");
        getContentPane().add(Studentportal);
        Studentportal.setBounds(300, 0, 170, 30);

        Welcomeback.setText("Welcome Back");
        getContentPane().add(Welcomeback);
        Welcomeback.setBounds(300, 30, 210, 16);

        Notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        Notification.setBorderPainted(false);
        Notification.setContentAreaFilled(false);
        Notification.addActionListener(this::NotificationActionPerformed);
        getContentPane().add(Notification);
        Notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        getContentPane().add(profile);
        profile.setBounds(1470, 10, 50, 40);

        paymenthistory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        paymenthistory.setForeground(new java.awt.Color(255, 255, 255));
        paymenthistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paymenthistory.png"))); // NOI18N
        paymenthistory.setText("Payment History");
        paymenthistory.setBorderPainted(false);
        paymenthistory.setContentAreaFilled(false);
        getContentPane().add(paymenthistory);
        paymenthistory.setBounds(-20, 600, 270, 43);

        paymenthistorypanel.setBackground(new java.awt.Color(255, 255, 255));
        paymenthistorypanel.setLayout(null);

        transactionhistorylabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transactionhistorylabel.setText("Transaction History");
        paymenthistorypanel.add(transactionhistorylabel);
        transactionhistorylabel.setBounds(21, 15, 290, 20);

        paymenthistorytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment Id", "Date", "Amount", "Status"
            }
        ));
        paymenthistorytablescrollpanel.setViewportView(paymenthistorytable);

        paymenthistorypanel.add(paymenthistorytablescrollpanel);
        paymenthistorytablescrollpanel.setBounds(20, 70, 1160, 450);

        getContentPane().add(paymenthistorypanel);
        paymenthistorypanel.setBounds(310, 260, 1200, 550);

        descriptionpanel.setBackground(new java.awt.Color(37, 99, 235));
        descriptionpanel.setLayout(null);

        paymentdetailslabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentdetailslabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentdetailslabel.setText("Payement Details");
        descriptionpanel.add(paymentdetailslabel);
        paymentdetailslabel.setBounds(30, 20, 216, 40);

        desc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        desc.setForeground(new java.awt.Color(190, 219, 255));
        desc.setText("Monitor your payments and dues.");
        descriptionpanel.add(desc);
        desc.setBounds(30, 70, 430, 20);

        getContentPane().add(descriptionpanel);
        descriptionpanel.setBounds(310, 80, 1200, 120);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        Background.setMinimumSize(new java.awt.Dimension(850, 90));
        Background.setPreferredSize(new java.awt.Dimension(950, 90));
        getContentPane().add(Background);
        Background.setBounds(0, -10, 1550, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewPaymentDetails().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Dashboard;
    private javax.swing.JButton Dashboard1;
    private javax.swing.JButton MealRoutine;
    private javax.swing.JButton MyComplaints;
    private javax.swing.JButton Myprofile;
    private javax.swing.JLabel Navigation;
    private javax.swing.JButton Notice;
    private javax.swing.JButton Notification;
    private javax.swing.JButton RoomDetails;
    private javax.swing.JLabel Studentportal;
    private javax.swing.JLabel Welcomeback;
    private javax.swing.JLabel desc;
    private javax.swing.JPanel descriptionpanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton makepayment;
    private javax.swing.JLabel paymentdetailslabel;
    private javax.swing.JButton paymenthistory;
    private javax.swing.JPanel paymenthistorypanel;
    private javax.swing.JTable paymenthistorytable;
    private javax.swing.JScrollPane paymenthistorytablescrollpanel;
    private javax.swing.JButton profile;
    private javax.swing.JLabel transactionhistorylabel;
    // End of variables declaration//GEN-END:variables

 public void setWelcomeUser(String username) { Welcomeback.setText("Welcome back, " + username + "!"); }
    public javax.swing.JTable getPaymentHistoryTable() { return paymenthistorytable; }

    public void DashboardListener(java.awt.event.ActionListener l)    { Dashboard.addActionListener(l); }
    public void MyComplaintsListener(java.awt.event.ActionListener l) { MyComplaints.addActionListener(l); }
    public void MealRoutineListener(java.awt.event.ActionListener l)  { MealRoutine.addActionListener(l); }
    public void NoticeListener(java.awt.event.ActionListener l)       { Notice.addActionListener(l); }
    public void RoomDetailsListener(java.awt.event.ActionListener l)  { RoomDetails.addActionListener(l); }
    public void MakePaymentListener(java.awt.event.ActionListener l)  { makepayment.addActionListener(l); }
    public void PaymentHistoryListener(java.awt.event.ActionListener l){ paymenthistory.addActionListener(l); }
    public void MyProfileListener(java.awt.event.ActionListener l)    { Myprofile.addActionListener(l); }
    public void ProfileListener(java.awt.event.ActionListener l)      { profile.addActionListener(l); }
    public void SignOutListener(java.awt.event.ActionListener l)      { Dashboard1.addActionListener(l); }

}

