/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author Hridayash
 */
public class ViewNotice extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewNotice.class.getName());

    /**
     * Creates new form AddStudentDetails
     */
    public ViewNotice() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundpanel = new javax.swing.JPanel();
        notification = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        studentportal = new javax.swing.JLabel();
        welcomeback = new javax.swing.JLabel();
        dashboard = new javax.swing.JButton();
        mycomplaints = new javax.swing.JButton();
        mealroutine = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        roomdetails = new javax.swing.JButton();
        myprofile = new javax.swing.JButton();
        cityscape = new javax.swing.JLabel();
        navigation = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        noticeboard = new javax.swing.JLabel();
        noticedesc = new javax.swing.JLabel();
        pinnednotices = new javax.swing.JScrollPane();
        pinnednoticepanel = new javax.swing.JPanel();
        pinnednotice = new javax.swing.JLabel();
        pinnednotice1 = new javax.swing.JPanel();
        pinnednotice2 = new javax.swing.JPanel();
        allnotices = new javax.swing.JScrollPane();
        allnoticepanel = new javax.swing.JPanel();
        allnoticescrollpane = new javax.swing.JScrollPane();
        allnotice = new javax.swing.JPanel();
        viewnotice = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        noticetitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateofissue = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        priority = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        getContentPane().setLayout(null);

        backgroundpanel.setLayout(null);

        notification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notification.png"))); // NOI18N
        notification.setBorderPainted(false);
        notification.setContentAreaFilled(false);
        notification.addActionListener(this::notificationActionPerformed);
        backgroundpanel.add(notification);
        notification.setBounds(1440, 10, 30, 40);

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/profile.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        backgroundpanel.add(profile);
        profile.setBounds(1480, 10, 41, 40);

        studentportal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentportal.setText("Student Portal");
        backgroundpanel.add(studentportal);
        studentportal.setBounds(300, 0, 170, 30);

        welcomeback.setText("Welcome Back");
        backgroundpanel.add(welcomeback);
        welcomeback.setBounds(300, 30, 240, 16);

        dashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorderPainted(false);
        dashboard.setContentAreaFilled(false);
        dashboard.addActionListener(this::dashboardActionPerformed);
        backgroundpanel.add(dashboard);
        dashboard.setBounds(-40, 210, 250, 43);

        mycomplaints.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mycomplaints.setForeground(new java.awt.Color(255, 255, 255));
        mycomplaints.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/my complaints.png"))); // NOI18N
        mycomplaints.setText("My Complaints\n");
        mycomplaints.setBorderPainted(false);
        mycomplaints.setContentAreaFilled(false);
        backgroundpanel.add(mycomplaints);
        mycomplaints.setBounds(-30, 280, 270, 43);

        mealroutine.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mealroutine.setForeground(new java.awt.Color(255, 255, 255));
        mealroutine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/meal routine.png"))); // NOI18N
        mealroutine.setText("Meal Routine");
        mealroutine.setBorderPainted(false);
        mealroutine.setContentAreaFilled(false);
        backgroundpanel.add(mealroutine);
        mealroutine.setBounds(-30, 350, 250, 43);

        notice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notice.setForeground(new java.awt.Color(255, 255, 255));
        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/notice.png"))); // NOI18N
        notice.setText("Notice");
        notice.setBorderPainted(false);
        notice.setContentAreaFilled(false);
        backgroundpanel.add(notice);
        notice.setBounds(0, 420, 140, 43);

        roomdetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        roomdetails.setForeground(new java.awt.Color(255, 255, 255));
        roomdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/roomdetails.png"))); // NOI18N
        roomdetails.setText("Room Details");
        roomdetails.setBorderPainted(false);
        roomdetails.setContentAreaFilled(false);
        backgroundpanel.add(roomdetails);
        roomdetails.setBounds(-20, 490, 230, 43);

        myprofile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myprofile.setForeground(new java.awt.Color(255, 255, 255));
        myprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/myprofile.png"))); // NOI18N
        myprofile.setText("My Profile");
        myprofile.setBorderPainted(false);
        myprofile.setContentAreaFilled(false);
        backgroundpanel.add(myprofile);
        myprofile.setBounds(0, 560, 160, 43);

        cityscape.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cityscape.setForeground(new java.awt.Color(255, 255, 255));
        cityscape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo.png"))); // NOI18N
        cityscape.setText("Cityscape");
        backgroundpanel.add(cityscape);
        cityscape.setBounds(20, 10, 150, 36);

        navigation.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        navigation.setForeground(new java.awt.Color(81, 162, 255));
        navigation.setText("NAVIGATION");
        backgroundpanel.add(navigation);
        navigation.setBounds(20, 180, 70, 16);

        signout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signout.setForeground(new java.awt.Color(255, 255, 255));
        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sign out.png"))); // NOI18N
        signout.setText("Sign Out");
        signout.setBorderPainted(false);
        signout.setContentAreaFilled(false);
        backgroundpanel.add(signout);
        signout.setBounds(0, 780, 170, 43);

        noticeboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noticeboard.setText("Notice Board");
        backgroundpanel.add(noticeboard);
        noticeboard.setBounds(310, 90, 120, 25);

        noticedesc.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        noticedesc.setForeground(new java.awt.Color(153, 161, 175));
        noticedesc.setText("Stay updated with hostel announcements");
        backgroundpanel.add(noticedesc);
        noticedesc.setBounds(310, 110, 270, 30);

        pinnednotices.setBackground(new java.awt.Color(255, 255, 255));

        pinnednoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        pinnednoticepanel.setLayout(null);

        pinnednotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pinnedmessage.png"))); // NOI18N
        pinnednotice.setText("Pinned Notice");
        pinnednoticepanel.add(pinnednotice);
        pinnednotice.setBounds(10, 10, 110, 24);

        pinnednotice1.setBackground(new java.awt.Color(191, 219, 254));
        pinnednotice1.setLayout(null);
        pinnednoticepanel.add(pinnednotice1);
        pinnednotice1.setBounds(10, 50, 1180, 50);

        pinnednotice2.setBackground(new java.awt.Color(191, 219, 254));
        pinnednotice2.setLayout(null);
        pinnednoticepanel.add(pinnednotice2);
        pinnednotice2.setBounds(10, 120, 1180, 50);

        pinnednotices.setViewportView(pinnednoticepanel);

        backgroundpanel.add(pinnednotices);
        pinnednotices.setBounds(310, 170, 1210, 200);

        allnotices.setBackground(new java.awt.Color(255, 255, 255));

        allnoticepanel.setBackground(new java.awt.Color(255, 255, 255));
        allnoticepanel.setLayout(null);

        allnotice.setBackground(new java.awt.Color(255, 255, 255));
        allnotice.setLayout(null);

        viewnotice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/viewnotice.png"))); // NOI18N
        viewnotice.setBorderPainted(false);
        viewnotice.setContentAreaFilled(false);
        allnotice.add(viewnotice);
        viewnotice.setBounds(1060, 40, 24, 24);

        jPanel3.setLayout(null);

        noticetitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noticetitle.setText("Hostel Fee Payment Deadline ");
        jPanel3.add(noticetitle);
        noticetitle.setBounds(20, 10, 250, 16);

        jLabel2.setText("All hostel residents are reminded that the hostel fee for May 2025 must be paid by May 15, 2025. Late payments will incur a penalty of ₹500 per week.");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 30, 1000, 16);

        dateofissue.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dateofissue.setText("Apr 28, 2025 ");
        jPanel3.add(dateofissue);
        dateofissue.setBounds(20, 60, 100, 14);

        category.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        category.setText("Finance");
        jPanel3.add(category);
        category.setBounds(120, 60, 80, 14);

        priority.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        priority.setText("Urgent");
        jPanel3.add(priority);
        priority.setBounds(220, 60, 60, 14);

        allnotice.add(jPanel3);
        jPanel3.setBounds(30, 20, 1130, 80);

        allnoticescrollpane.setViewportView(allnotice);

        allnoticepanel.add(allnoticescrollpane);
        allnoticescrollpane.setBounds(12, 12, 1180, 340);

        allnotices.setViewportView(allnoticepanel);

        backgroundpanel.add(allnotices);
        allnotices.setBounds(310, 430, 1210, 370);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.png"))); // NOI18N
        backgroundpanel.add(background);
        background.setBounds(0, 0, 1550, 840);

        getContentPane().add(backgroundpanel);
        backgroundpanel.setBounds(0, 0, 1550, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notificationActionPerformed

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewNotice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allnotice;
    private javax.swing.JPanel allnoticepanel;
    private javax.swing.JScrollPane allnotices;
    private javax.swing.JScrollPane allnoticescrollpane;
    private javax.swing.JLabel background;
    private javax.swing.JPanel backgroundpanel;
    private javax.swing.JLabel category;
    private javax.swing.JLabel cityscape;
    private javax.swing.JButton dashboard;
    private javax.swing.JLabel dateofissue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mealroutine;
    private javax.swing.JButton mycomplaints;
    private javax.swing.JButton myprofile;
    private javax.swing.JLabel navigation;
    private javax.swing.JButton notice;
    private javax.swing.JLabel noticeboard;
    private javax.swing.JLabel noticedesc;
    private javax.swing.JLabel noticetitle;
    private javax.swing.JButton notification;
    private javax.swing.JLabel pinnednotice;
    private javax.swing.JPanel pinnednotice1;
    private javax.swing.JPanel pinnednotice2;
    private javax.swing.JPanel pinnednoticepanel;
    private javax.swing.JScrollPane pinnednotices;
    private javax.swing.JLabel priority;
    private javax.swing.JButton profile;
    private javax.swing.JButton roomdetails;
    private javax.swing.JButton signout;
    private javax.swing.JLabel studentportal;
    private javax.swing.JButton viewnotice;
    private javax.swing.JLabel welcomeback;
    // End of variables declaration//GEN-END:variables


// ── Panel accessors (controller dynamically builds notice cards into these) ───
public javax.swing.JPanel getPinnedNoticePanel() {
    return pinnednoticepanel;
}

public javax.swing.JPanel getAllNoticePanel() {
    return allnotice;
}

// ── Welcome label ─────────────────────────────────────────────────────────────
public void setWelcomeUser(String username) {
    welcomeback.setText("Welcome Back, " + username);
}

// ── Button listeners ─────────────────────────────────────────────────────────
public void DashboardListener(java.awt.event.ActionListener listener) {
    dashboard.addActionListener(listener);
}

public void NoticeListener(java.awt.event.ActionListener listener) {
    notice.addActionListener(listener);
}

public void MyProfileListener(java.awt.event.ActionListener listener) {
    myprofile.addActionListener(listener);
}

public void ProfileListener(java.awt.event.ActionListener listener) {
    profile.addActionListener(listener);
}

public void SignOutListener(java.awt.event.ActionListener listener) {
    signout.addActionListener(listener);
}

public void NotificationListener(java.awt.event.ActionListener listener) {
    notification.addActionListener(listener);
}
}
