/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class ViewStudentExpand extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewStudentExpand.class.getName());

    /**
     * Creates new form IssueNotice
     */
    public ViewStudentExpand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewstudent = new javax.swing.JPanel();
        studentdetails = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();
        studentid = new javax.swing.JLabel();
        semesterpanel = new javax.swing.JPanel();
        Semester = new javax.swing.JLabel();
        semestervariable = new javax.swing.JLabel();
        roomnumberpanel = new javax.swing.JPanel();
        roomnumber = new javax.swing.JLabel();
        roomnumbervariable = new javax.swing.JLabel();
        phonepanel = new javax.swing.JPanel();
        phone = new javax.swing.JLabel();
        phonenumbervariable = new javax.swing.JLabel();
        feestatuspanel = new javax.swing.JPanel();
        feeststus = new javax.swing.JLabel();
        feeststusvariable = new javax.swing.JLabel();
        progeampanel = new javax.swing.JPanel();
        program = new javax.swing.JLabel();
        programvariable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        viewstudent.setBackground(new java.awt.Color(255, 255, 255));
        viewstudent.setLayout(null);

        studentdetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        studentdetails.setText("Student Details");
        viewstudent.add(studentdetails);
        studentdetails.setBounds(10, 10, 150, 16);

        Name.setText("Hridayash Shrestha");
        viewstudent.add(Name);
        Name.setBounds(10, 40, 120, 16);

        closebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closebutton.setText("Close");
        viewstudent.add(closebutton);
        closebutton.setBounds(10, 250, 330, 30);

        studentid.setText("Student id-1");
        viewstudent.add(studentid);
        studentid.setBounds(10, 60, 80, 16);

        semesterpanel.setBackground(new java.awt.Color(248, 250, 252));
        semesterpanel.setLayout(null);

        Semester.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Semester.setForeground(new java.awt.Color(153, 161, 175));
        Semester.setText("Semester");
        semesterpanel.add(Semester);
        Semester.setBounds(0, 0, 60, 14);

        semestervariable.setText("1st");
        semesterpanel.add(semestervariable);
        semestervariable.setBounds(0, 10, 120, 30);

        viewstudent.add(semesterpanel);
        semesterpanel.setBounds(180, 90, 150, 40);

        roomnumberpanel.setBackground(new java.awt.Color(248, 250, 252));
        roomnumberpanel.setLayout(null);

        roomnumber.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        roomnumber.setForeground(new java.awt.Color(153, 161, 175));
        roomnumber.setText("Room no");
        roomnumberpanel.add(roomnumber);
        roomnumber.setBounds(0, 0, 60, 14);

        roomnumbervariable.setText("101");
        roomnumberpanel.add(roomnumbervariable);
        roomnumbervariable.setBounds(0, 10, 120, 30);

        viewstudent.add(roomnumberpanel);
        roomnumberpanel.setBounds(10, 150, 150, 40);

        phonepanel.setBackground(new java.awt.Color(248, 250, 252));
        phonepanel.setLayout(null);

        phone.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        phone.setForeground(new java.awt.Color(153, 161, 175));
        phone.setText("Phone");
        phonepanel.add(phone);
        phone.setBounds(0, 0, 60, 14);

        phonenumbervariable.setText("980000000");
        phonepanel.add(phonenumbervariable);
        phonenumbervariable.setBounds(0, 10, 140, 30);

        viewstudent.add(phonepanel);
        phonepanel.setBounds(180, 150, 150, 40);

        feestatuspanel.setBackground(new java.awt.Color(248, 250, 252));
        feestatuspanel.setLayout(null);

        feeststus.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        feeststus.setForeground(new java.awt.Color(153, 161, 175));
        feeststus.setText("Fee Status");
        feestatuspanel.add(feeststus);
        feeststus.setBounds(0, 0, 60, 14);

        feeststusvariable.setText("Pending");
        feestatuspanel.add(feeststusvariable);
        feeststusvariable.setBounds(0, 10, 120, 30);

        viewstudent.add(feestatuspanel);
        feestatuspanel.setBounds(10, 200, 150, 40);

        progeampanel.setBackground(new java.awt.Color(248, 250, 252));
        progeampanel.setLayout(null);

        program.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        program.setForeground(new java.awt.Color(153, 161, 175));
        program.setText("Program");
        progeampanel.add(program);
        program.setBounds(0, 0, 60, 14);

        programvariable.setText("Computing");
        progeampanel.add(programvariable);
        programvariable.setBounds(0, 10, 120, 30);

        viewstudent.add(progeampanel);
        progeampanel.setBounds(10, 90, 150, 40);

        getContentPane().add(viewstudent);
        viewstudent.setBounds(0, 0, 350, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewStudentExpand().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Semester;
    private javax.swing.JButton closebutton;
    private javax.swing.JPanel feestatuspanel;
    private javax.swing.JLabel feeststus;
    private javax.swing.JLabel feeststusvariable;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phonenumbervariable;
    private javax.swing.JPanel phonepanel;
    private javax.swing.JPanel progeampanel;
    private javax.swing.JLabel program;
    private javax.swing.JLabel programvariable;
    private javax.swing.JLabel roomnumber;
    private javax.swing.JPanel roomnumberpanel;
    private javax.swing.JLabel roomnumbervariable;
    private javax.swing.JPanel semesterpanel;
    private javax.swing.JLabel semestervariable;
    private javax.swing.JLabel studentdetails;
    private javax.swing.JLabel studentid;
    private javax.swing.JPanel viewstudent;
    // End of variables declaration//GEN-END:variables
public void setStudentData(model.UserData u) {
    Name.setText(u.getFullName() != null && !u.getFullName().isEmpty()
            ? u.getFullName() : u.getUsername());
    studentid.setText("Student id-" + u.getId());
    semestervariable.setText(u.getSemester() != null ? u.getSemester() : "—");
    programvariable.setText(u.getProgram() != null ? u.getProgram() : "—");
    phonenumbervariable.setText(u.getPhone() != null ? u.getPhone() : "—");
    // Room number comes from room allocation — show placeholder for now
    roomnumbervariable.setText("—");
    feeststusvariable.setText("Pending");
}
 
/** Wires the Close button */
public void CloseListener(java.awt.event.ActionListener listener) {
    closebutton.addActionListener(listener);
}
}
