/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hridayash
 */
public class viewnoticeexpand extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewnoticeexpand.class.getName());

    /**
     * Creates new form viewnoticeexpand
     **/
    public viewnoticeexpand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expandnotice = new javax.swing.JPanel();
        priority = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        description = new javax.swing.JScrollPane();
        descriptiontextarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        expandnotice.setBackground(new java.awt.Color(255, 255, 255));
        expandnotice.setLayout(null);

        priority.setText("Urgent");
        expandnotice.add(priority);
        priority.setBounds(10, 10, 70, 20);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Title.setText("Notice Title");
        expandnotice.add(Title);
        Title.setBounds(10, 50, 370, 20);

        date.setText("date");
        expandnotice.add(date);
        date.setBounds(10, 80, 110, 16);

        category.setText("category");
        expandnotice.add(category);
        category.setBounds(130, 80, 110, 16);

        close.setBackground(new java.awt.Color(99, 102, 255));
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Close");
        expandnotice.add(close);
        close.setBounds(10, 230, 380, 23);

        descriptiontextarea.setEditable(false);
        descriptiontextarea.setColumns(20);
        descriptiontextarea.setLineWrap(true);
        descriptiontextarea.setRows(5);
        descriptiontextarea.setWrapStyleWord(true);
        descriptiontextarea.setFocusable(false);
        description.setViewportView(descriptiontextarea);

        expandnotice.add(description);
        description.setBounds(10, 130, 380, 70);

        getContentPane().add(expandnotice);
        expandnotice.setBounds(-1, -1, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewnoticeexpand().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel category;
    private javax.swing.JButton close;
    private javax.swing.JLabel date;
    private javax.swing.JScrollPane description;
    private javax.swing.JTextArea descriptiontextarea;
    private javax.swing.JPanel expandnotice;
    private javax.swing.JLabel priority;
    // End of variables declaration//GEN-END:variables

public void setNoticeData(model.NoticeData n) {
    Title.setText(n.getTitle());
    date.setText(n.getFormattedDate());
    category.setText(n.getCategory());
    priority.setText(n.getPriority());
   
    descriptiontextarea.setText(n.getDescription());
    descriptiontextarea.setCaretPosition(0);
}
 
/** Wires the Close button */
public void CloseListener(java.awt.event.ActionListener listener) {
    close.addActionListener(listener);
}
}
